// Code generated by ent, DO NOT EDIT.

package workflowinstance

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the workflowinstance type in the database.
	Label = "workflow_instance"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// Table holds the table name of the workflowinstance in the database.
	Table = "workflow_instances"
)

// Columns holds all SQL columns for workflowinstance fields.
var Columns = []string{
	FieldID,
	FieldStatus,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the WorkflowInstance queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}
