version: "2"
run:
  allow-serial-runners: true
linters:
  enable:
    - bodyclose
    - err113
    - gocritic
    - gocyclo
    - gosec
    - misspell
    - mnd
    - noctx
    - revive
    - staticcheck
    - whitespace
    - wsl
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - vanilla/*
      - .buildkite/*
      - .github/*
      - templates/*
      - third_party$
      - builtin$
      - examples$
issues:
  fix: true
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofumpt:
      extra-rules: true
    goimports:
      local-prefixes:
        - github.com/theopenlane/entx
  exclusions:
    generated: lax
    paths:
      - vanilla/*
      - .buildkite/*
      - .github/*
      - templates/*
      - third_party$
      - builtin$
      - examples$
