version: '3'

includes:
  example:
    taskfile: ./vanilla/_example/Taskfile.yml
    dir: ./vanilla/_example

tasks:
  go:lint:
    desc: runs golangci-lint, the most annoying opinionated linter ever
    cmds:
      - golangci-lint run --config=.golangci.yaml --verbose

  go:test:
    desc: runs and outputs results of created go tests
    cmds:
      - go test -v ./...

  go:tidy:
    desc: runs go mod tidy on the backend
    aliases: [tidy]
    cmds:
      - go mod tidy

  go:all:
    aliases: [go]
    desc: runs all go test and lint related tasks
    cmds:
      - task: go:tidy
      - task: go:lint
      - task: go:test

  precommit-full:
    desc: Lint the project against all files
    cmds:
      - pre-commit install && pre-commit install-hooks
      - pre-commit autoupdate
      - pre-commit run --show-diff-on-failure --color=always --all-files
