// Code generated by entx/entityops. DO NOT EDIT.

package {{ .PackageName }}

import (
	"context"
	"encoding/json"

	"{{ .ContextxPackage }}"
	"{{ .GalaPackage }}"
)

// EntityOperationMetadata captures execution provenance for entity operations.
// Identity and authorization context (org, user, permissions) come from
// auth.Caller in context, not from this struct.
type EntityOperationMetadata struct {
	// Operation is the mutation type: CREATE, UPDATE, DELETE
	Operation string `json:"operation,omitempty"`
	// Schema is the target entity schema
	Schema SchemaDescriptor `json:"schema"`
	// EntityID is the target entity identifier
	EntityID string `json:"entityId,omitempty"`
	// IntegrationID is the source integration identifier
	IntegrationID string `json:"integrationId,omitempty"`
	// DefinitionID is the integration definition identifier
	DefinitionID string `json:"definitionId,omitempty"`
	// RunID is the integration run identifier
	RunID string `json:"runId,omitempty"`
	// Variant is the integration variant
	Variant string `json:"variant,omitempty"`
	// Webhook is the webhook URL for delivery tracking
	Webhook string `json:"webhook,omitempty"`
	// WebhookEvent is the webhook event name
	WebhookEvent string `json:"webhookEvent,omitempty"`
	// DeliveryID is the delivery tracking identifier
	DeliveryID string `json:"deliveryId,omitempty"`
	// WorkflowInstanceID is the source workflow instance identifier
	WorkflowInstanceID string `json:"workflowInstanceId,omitempty"`
	// WorkflowActionKey is the workflow action key that initiated this operation
	WorkflowActionKey string `json:"workflowActionKey,omitempty"`
	// WorkflowActionIdx is the workflow action index
	WorkflowActionIdx int `json:"workflowActionIndex,omitempty"`
	// WorkflowObjectID is the workflow target object identifier
	WorkflowObjectID string `json:"workflowObjectId,omitempty"`
	// WorkflowObjectType is the workflow target object type
	WorkflowObjectType string `json:"workflowObjectType,omitempty"`
}

// --- Context propagation ---

// OperationMetadataKey stores durable entity operation metadata on a context
var OperationMetadataKey = contextx.NewKey[EntityOperationMetadata]()

// WithOperationMetadata stores metadata on the supplied context
func WithOperationMetadata(ctx context.Context, meta EntityOperationMetadata) context.Context {
	return OperationMetadataKey.Set(ctx, meta)
}

// OperationMetadataFromContext returns entity operation metadata from context when present
func OperationMetadataFromContext(ctx context.Context) (EntityOperationMetadata, bool) {
	return OperationMetadataKey.Get(ctx)
}

// --- Gala context codec ---

const operationMetadataCodecID = gala.ContextKey("entity_operation")

// ContextCodecs returns the durable context codecs required by entity operation dispatch and listeners
func ContextCodecs() []gala.ContextCodec {
	return []gala.ContextCodec{
		gala.NewKeyCodec(operationMetadataCodecID, OperationMetadataKey),
	}
}
