// Code generated by entx/entityops. DO NOT EDIT.

package {{ .PackageName }}

import "{{ .GalaPackage }}"

// IngestTopics is the namespace for every generated asynchronous schema-ingest topic.
var IngestTopics = gala.IntegrationIngest.At("entityops")

{{- range $schema := .Schemas }}
{{- if $schema.IntegrationMapped }}

// {{ $schema.Name }}Fields indexes the provider-mappable fields of {{ $schema.Name }}
var {{ $schema.Name }}Fields = struct {
{{- range $schema.ObjectFields }}
{{- if and .IntegrationMapped (not .SystemControlled) }}
	// {{ .Name }} is the {{ .Snake }} field
	{{ .Name }} FieldDescriptor
{{- end }}
{{- end }}
}{
{{- range $schema.ObjectFields }}
{{- if and .IntegrationMapped (not .SystemControlled) }}
	{{ .Name }}: FieldDescriptor{Name: "{{ .Snake }}", InputKey: "{{ .InputKey }}"},
{{- end }}
{{- end }}
}
{{- end }}
{{- end }}
