// Code generated by entx/entityops. DO NOT EDIT.
// This file keeps the WorkflowObjectType enum in lockstep with the schemas that carry workflow support.

package {{ .EnumsPackageName }}

import (
	"fmt"
	"io"
)

// WorkflowObjectType enumerates supported object types for workflows.
// These types are automatically generated based on entities that have workflow-eligible fields.
type WorkflowObjectType string

var (
{{- range .Schemas }}
{{- if .WorkflowEligible }}
	WorkflowObjectType{{ .Name }} WorkflowObjectType = "{{ .Name }}"
{{- end }}
{{- end }}
)

var WorkflowObjectTypes = []string{
{{- range .Schemas }}
{{- if .WorkflowEligible }}
	string(WorkflowObjectType{{ .Name }}),
{{- end }}
{{- end }}
}

// Values returns all workflow object type values.
func (WorkflowObjectType) Values() (vals []string) {
	return WorkflowObjectTypes
}

// String returns the string representation of the workflow object type.
func (r WorkflowObjectType) String() string { return string(r) }

// ToWorkflowObjectType converts a string to a WorkflowObjectType pointer.
func ToWorkflowObjectType(v string) *WorkflowObjectType {
	switch v {
{{- range .Schemas }}
{{- if .WorkflowEligible }}
	case WorkflowObjectType{{ .Name }}.String():
		return &WorkflowObjectType{{ .Name }}
{{- end }}
{{- end }}
	default:
		return nil
	}
}

// MarshalGQL marshals the workflow object type to GraphQL.
func (r WorkflowObjectType) MarshalGQL(w io.Writer) {
	_, _ = w.Write([]byte("\"" + r.String() + "\""))
}

// UnmarshalGQL unmarshals the workflow object type from GraphQL.
func (r *WorkflowObjectType) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("%w, got: %T", ErrWrongTypeWorkflowObjectType, v)
	}
	*r = WorkflowObjectType(str)
	return nil
}
