// Code generated by entx/entityops. DO NOT EDIT.

package {{ .PackageName }}

import (
	"slices"

	"entgo.io/ent"
	"{{ .EntPackage }}"
	"{{ .EntPackage }}/workflowobjectref"
)

// EdgeChange describes one mutated edge and the IDs added or removed
type EdgeChange struct {
	// Edge is the mutated edge name
	Edge string `json:"edge" jsonschema:"description=Mutated edge name"`
	// AddedIDs are the IDs added to the edge
	AddedIDs []string `json:"addedIds,omitempty" jsonschema:"description=IDs added to the edge"`
	// RemovedIDs are the IDs removed from the edge; an empty non-nil slice means the edge was cleared
	RemovedIDs []string `json:"removedIds,omitempty" jsonschema:"description=IDs removed from the edge"`
}

// WorkflowEligible reports whether the schema participates in workflows via eligible fields or edges
func (s *Schema) WorkflowEligible() bool {
	return s.RefField != "" ||
		slices.ContainsFunc(s.Fields, func(f FieldDescriptor) bool { return f.WorkflowEligible }) ||
		slices.ContainsFunc(s.Edges, func(e EdgeDescriptor) bool { return e.WorkflowEligible })
}

// WorkflowFieldNames returns the snake_case names of this schema's workflow-eligible fields
func (s *Schema) WorkflowFieldNames() []string {
	var out []string

	for _, f := range s.Fields {
		if f.WorkflowEligible {
			out = append(out, f.Name)
		}
	}

	return out
}

// WorkflowFields returns this schema's workflow-eligible field descriptors (name, label, type), the
// descriptor analog of WorkflowFieldNames consumed by the workflow builder and proposal preview UI
func (s *Schema) WorkflowFields() []FieldDescriptor {
	var out []FieldDescriptor

	for _, f := range s.Fields {
		if f.WorkflowEligible {
			out = append(out, f)
		}
	}

	return out
}

// WorkflowEdgeNames returns the names of this schema's workflow-eligible edges
func (s *Schema) WorkflowEdgeNames() []string {
	var out []string

	for _, e := range s.Edges {
		if e.WorkflowEligible {
			out = append(out, e.Name)
		}
	}

	return out
}

// init wires workflow object-ref resolution onto each schema that has a WorkflowObjectRef edge
func init() {
{{- range .Schemas }}
{{- if .WorkflowRefField }}
	Schema{{ .Name }}.RefField = "{{ .WorkflowRefField }}"
	Schema{{ .Name }}.RefMatch = func(ref *generated.WorkflowObjectRef) (string, bool) {
		if ref.{{ .WorkflowRefField }}ID != "" {
			return ref.{{ .WorkflowRefField }}ID, true
		}

		return "", false
	}
	Schema{{ .Name }}.RefFilter = func(query *generated.WorkflowObjectRefQuery, objectID string) *generated.WorkflowObjectRefQuery {
		return query.Where(workflowobjectref.{{ .WorkflowRefField }}IDEQ(objectID))
	}
{{- end }}
{{- end }}
}

// ObjectFromWorkflowRef resolves the workflow object type and ID from a WorkflowObjectRef row by
// dispatching to each schema's generated RefMatch closure
func ObjectFromWorkflowRef(ref *generated.WorkflowObjectRef) (objectType string, objectID string, ok bool) {
	for _, schema := range allSchemas {
		if schema.RefMatch == nil {
			continue
		}

		if id, matched := schema.RefMatch(ref); matched {
			return schema.Name, id, true
		}
	}

	return "", "", false
}

// ExtractChangedEdges returns the workflow-eligible edges mutated by m, with the IDs added or removed
func ExtractChangedEdges(m ent.Mutation) []EdgeChange {
	schema, ok := LookupSchema(m.Type())
	if !ok {
		return nil
	}

	eligible := schema.WorkflowEdgeNames()
	if len(eligible) == 0 {
		return nil
	}

	changed := changedEdgeNames(m)

	var out []EdgeChange

	for _, edge := range eligible {
		if !slices.Contains(changed, edge) {
			continue
		}

		change := EdgeChange{Edge: edge}

		if ids := toStringIDs(m.AddedIDs(edge)); len(ids) > 0 {
			change.AddedIDs = ids
		}

		if ids := toStringIDs(m.RemovedIDs(edge)); len(ids) > 0 {
			change.RemovedIDs = ids
		}

		if m.EdgeCleared(edge) {
			change.RemovedIDs = []string{}
		}

		out = append(out, change)
	}

	return out
}

// changedEdgeNames returns the names of all edges touched by the mutation
func changedEdgeNames(m ent.Mutation) []string {
	var names []string

	names = append(names, m.AddedEdges()...)
	names = append(names, m.RemovedEdges()...)
	names = append(names, m.ClearedEdges()...)

	return names
}

// toStringIDs converts ent edge ID values to strings, dropping any non-string IDs
func toStringIDs(values []ent.Value) []string {
	if len(values) == 0 {
		return nil
	}

	ids := make([]string, 0, len(values))

	for _, value := range values {
		if id, ok := value.(string); ok {
			ids = append(ids, id)
		}
	}

	return ids
}
