// Code generated by entx/entityops. DO NOT EDIT.

package {{ .PackageName }}

import "{{ .GalaPackage }}"

// IngestTopics is the namespace for every generated asynchronous schema-ingest topic.
var IngestTopics = gala.NewTopicNamespace("entityops.", gala.JobKindIntegrationIngest)

{{- range $schema := .Schemas }}
{{- if $schema.IntegrationMapped }}

// Integration mapping input keys for {{ $schema.Name }}
const (
{{- range $schema.ObjectFields }}
{{- if .IntegrationMapped }}
	InputKey{{ $schema.Name }}{{ .InputGoField }} = {{ printf "%q" .InputKey }}
{{- end }}
{{- end }}
)
{{- end }}
{{- end }}
