// Code generated by entx/entityops. DO NOT EDIT.

package {{ .PackageName }}

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"
	"sync"

	"{{ .EntPackage }}"
	"{{ .JsonxPackage }}"
{{- range .Schemas }}
{{- if and .HasOwnerID .PredicateImport }}
	"{{ .PredicateImport }}"
{{- end }}
{{- end }}
)

// EntityRef is a lightweight reference to an entity
type EntityRef struct {
	// ID is the entity identifier
	ID string
	// Schema is the entity's schema descriptor
	Schema SchemaDescriptor
}

// Schema is the runtime representation of a registered entity schema.
// It carries the schema identity and all supported operation closures.
type Schema struct {
	SchemaDescriptor
	// Create creates a new entity from a JSON input and returns the entity ID
	Create func(ctx context.Context, client *generated.Client, input json.RawMessage) (string, error)
	// Update applies a typed update input to an entity by ID
	Update func(ctx context.Context, client *generated.Client, entityID string, input json.RawMessage) error
	// Query returns all entities of this schema within an organization as JSON
	Query func(ctx context.Context, client *generated.Client, orgID string) ([]json.RawMessage, error)
	// Load loads a single entity by ID and returns its JSON representation
	Load func(ctx context.Context, client *generated.Client, entityID string) (json.RawMessage, error)
	// Edges lists the linkable edges on this schema
	Edges []EdgeDescriptor
}

// normalizeFieldKeys re-keys a JSON object from snake_case to PascalCase field names
// so json.Unmarshal matches generated UpdateInput fields
func normalizeFieldKeys(raw json.RawMessage, keyMap map[string]string) json.RawMessage {
	if len(keyMap) == 0 || len(raw) == 0 {
		return raw
	}

	var m map[string]json.RawMessage
	if err := json.Unmarshal(raw, &m); err != nil {
		return raw
	}

	normalized := make(map[string]json.RawMessage, len(m))
	for k, v := range m {
		if pascal, ok := keyMap[k]; ok {
			normalized[pascal] = v
		} else {
			normalized[k] = v
		}
	}

	result, _ := json.Marshal(normalized)

	return result
}

// --- Per-schema descriptors (defined separately to avoid init cycles) ---

var (
{{- range .Schemas }}
	desc{{ .Name }} = SchemaDescriptor{
		Name:   "{{ .Name }}",
		Snake:  "{{ .Snake }}",
		Camel:  "{{ .Camel }}",
		Lower:  "{{ .Lower }}",
		Plural: "{{ .Plural }}",
		Table:  "{{ .Table }}",
		Label:  "{{ .Label }}",
	}
{{- end }}
)

// --- Per-schema field key maps (snake_case → PascalCase) ---

var (
{{- range .Schemas }}
{{- if .HasUpdate }}
	fieldKeys{{ .Name }} = map[string]string{
	{{- range .Fields }}
		"{{ .Snake }}": "{{ .Name }}",
	{{- end }}
	}
{{- end }}
{{- end }}
)

// --- Per-schema registrations ---

var (
{{- range $schema := .Schemas }}
	Schema{{ $schema.Name }} = &Schema{
		SchemaDescriptor: desc{{ .Name }},
{{- if .HasCreate }}
		Create: func(ctx context.Context, client *generated.Client, input json.RawMessage) (string, error) {
			ref := SchemaRef{Schema: "{{ .Snake }}", Operation: OpCreate}

			decoded, err := jsonx.Decode[generated.{{ .CreateInputType }}](input)
			if err != nil {
				return "", logError(ctx, ref, ErrDecodeFailed, err)
			}

			entity, err := client.{{ .Name }}.Create().SetInput(decoded).Save(ctx)
			if err != nil {
				return "", logPersistError(ctx, ref, ErrCreateFailed, err)
			}

			return entity.ID, nil
		},
{{- end }}
{{- if .HasUpdate }}
		Update: func(ctx context.Context, client *generated.Client, entityID string, input json.RawMessage) error {
			ref := SchemaRef{Schema: "{{ .Snake }}", Operation: OpUpdate, EntityID: entityID}

			decoded, err := jsonx.Decode[generated.{{ .UpdateInputType }}](normalizeFieldKeys(input, fieldKeys{{ .Name }}))
			if err != nil {
				return logError(ctx, ref, ErrDecodeFailed, err)
			}

			if err := client.{{ .Name }}.UpdateOneID(entityID).SetInput(decoded).Exec(ctx); err != nil {
				return logPersistError(ctx, ref, ErrUpdateFailed, err)
			}

			return nil
		},
{{- end }}
{{- if .HasOwnerID }}
		Query: func(ctx context.Context, client *generated.Client, orgID string) ([]json.RawMessage, error) {
			ref := SchemaRef{Schema: "{{ .Snake }}", Operation: OpQuery}

			entities, err := client.{{ .Name }}.Query().
				Where({{ .PredicatePackage }}.OwnerID(orgID)).
				All(ctx)
			if err != nil {
				return nil, logError(ctx, ref, ErrQueryFailed, err)
			}

			results := make([]json.RawMessage, 0, len(entities))
			for _, e := range entities {
				data, err := json.Marshal(e)
				if err != nil {
					logError(ctx, ref, ErrMarshalFailed, err)
					continue
				}

				results = append(results, data)
			}

			return results, nil
		},
{{- end }}
		Load: func(ctx context.Context, client *generated.Client, entityID string) (json.RawMessage, error) {
			ref := SchemaRef{Schema: "{{ .Snake }}", Operation: OpLoad, EntityID: entityID}

			entity, err := client.{{ .Name }}.Get(ctx, entityID)
			if err != nil {
				return nil, logError(ctx, ref, ErrLoadFailed, err)
			}

			data, err := json.Marshal(entity)
			if err != nil {
				return nil, logError(ctx, ref, ErrMarshalFailed, err)
			}

			return data, nil
		},
	}
{{- end }}
)

// init wires cross-schema edge references after all Schema vars are initialized
func init() {
{{- range $schema := .Schemas }}
{{- if .Edges }}
	Schema{{ $schema.Name }}.Edges = []EdgeDescriptor{
{{- range .Edges }}
		{
			Name: "{{ .Name }}",
{{- if .TargetEligible }}
			Target: Schema{{ .TargetSchema }},
{{- end }}
			Relationship: "{{ .Relationship }}",
			Link: func(ctx context.Context, client *generated.Client, entityID string, targetIDs ...string) error {
				if err := client.{{ $schema.Name }}.UpdateOneID(entityID).Add{{ .Name | pascal | singular }}IDs(targetIDs...).Exec(ctx); err != nil {
					return logPersistError(ctx, SchemaRef{Schema: "{{ $schema.Snake }}", Operation: OpLink, EntityID: entityID, Edge: "{{ .Name }}"}, ErrLinkFailed, err)
				}

				return nil
			},
			Unlink: func(ctx context.Context, client *generated.Client, entityID string, targetIDs ...string) error {
				if err := client.{{ $schema.Name }}.UpdateOneID(entityID).Remove{{ .Name | pascal | singular }}IDs(targetIDs...).Exec(ctx); err != nil {
					return logPersistError(ctx, SchemaRef{Schema: "{{ $schema.Snake }}", Operation: OpUnlink, EntityID: entityID, Edge: "{{ .Name }}"}, ErrUnlinkFailed, err)
				}

				return nil
			},
			Query: func(ctx context.Context, client *generated.Client, entityID string) ([]string, error) {
				entity, err := client.{{ $schema.Name }}.Get(ctx, entityID)
				if err != nil {
					return nil, logError(ctx, SchemaRef{Schema: "{{ $schema.Snake }}", Operation: OpQuery, EntityID: entityID, Edge: "{{ .Name }}"}, ErrLoadFailed, err)
				}

				return entity.Query{{ .Name | pascal }}().IDs(ctx)
			},
		},
{{- end }}
	}
{{- end }}
{{- end }}
}

// --- Lookup registry ---

var allSchemas = []*Schema{
{{- range .Schemas }}
	Schema{{ .Name }},
{{- end }}
}

var (
	schemaLookupOnce sync.Once
	schemaLookupMap  map[string]*Schema
)

func buildSchemaLookup() {
	schemaLookupOnce.Do(func() {
		schemaLookupMap = make(map[string]*Schema, len(allSchemas)*4)

		for _, s := range allSchemas {
			schemaLookupMap[s.Name] = s
			schemaLookupMap[s.Snake] = s
			schemaLookupMap[s.Camel] = s
			schemaLookupMap[s.Lower] = s
		}
	})
}

// LookupSchema resolves a schema by any known name variation (PascalCase, snake_case,
// camelCase, or lowercase). Returns the schema and whether a match was found.
func LookupSchema(name string) (*Schema, bool) {
	buildSchemaLookup()

	if s, ok := schemaLookupMap[name]; ok {
		return s, true
	}

	normalized := strings.ToLower(strings.NewReplacer("_", "", "-", "", " ", "").Replace(name))

	if s, ok := schemaLookupMap[normalized]; ok {
		return s, true
	}

	return nil, false
}

// AllSchemas returns a copy of all registered schemas
func AllSchemas() []*Schema {
	result := make([]*Schema, len(allSchemas))
	copy(result, allSchemas)

	return result
}

// SelectTargets queries entities matching a target selector and filters them
// using the provided expression evaluator
func SelectTargets(ctx context.Context, client *generated.Client, orgID string, selector TargetSelector, eval ExpressionEvaluator) ([]EntityRef, error) {
	schema, ok := LookupSchema(selector.Schema.Name)
	if !ok {
		return nil, fmt.Errorf("%w: %s", ErrSchemaNotFound, selector.Schema.Name)
	}

	if schema.Query == nil {
		return nil, fmt.Errorf("%w: %s", ErrQueryUnsupported, schema.Name)
	}

	entities, err := schema.Query(ctx, client, orgID)
	if err != nil {
		return nil, err
	}

	excludeSet := make(map[string]struct{}, len(selector.ExcludeIDs))
	for _, id := range selector.ExcludeIDs {
		excludeSet[id] = struct{}{}
	}

	ref := SchemaRef{Schema: schema.Snake, Operation: OpQuery}
	var results []EntityRef

	for _, data := range entities {
		var parsed struct {
			ID string `json:"id"`
		}

		if err := json.Unmarshal(data, &parsed); err != nil {
			logError(ctx, ref, ErrDecodeFailed, err)
			continue
		}

		if _, excluded := excludeSet[parsed.ID]; excluded {
			continue
		}

		if selector.Expression != "" {
			match, evalErr := EvaluateWithOptionalSource(ctx, eval, selector.Expression, data, selector.SourceContext)
			if evalErr != nil {
				logError(ctx, SchemaRef{Schema: schema.Snake, Operation: OpQuery, EntityID: parsed.ID}, ErrEvaluationFailed, evalErr)
				continue
			}

			if !match {
				continue
			}
		}

		results = append(results, EntityRef{ID: parsed.ID, Schema: schema.SchemaDescriptor})
	}

	return results, nil
}

// EvaluateWithOptionalSource dispatches to SourceAwareExpressionEvaluator when source context is
// present, otherwise falls back to the standard ExpressionEvaluator
func EvaluateWithOptionalSource(ctx context.Context, eval ExpressionEvaluator, expression string, targetData json.RawMessage, sourceContext json.RawMessage) (bool, error) {
	if len(sourceContext) > 0 {
		if sa, ok := eval.(SourceAwareExpressionEvaluator); ok {
			return sa.EvaluateBoolWithSource(ctx, expression, targetData, sourceContext)
		}
	}

	return eval.EvaluateBool(ctx, expression, targetData)
}
