// Code generated by entx/entityops. DO NOT EDIT.

package {{ .PackageName }}

import (
	"encoding/json"
	"fmt"
)

// SchemaDescriptor is the canonical identity for an entity schema
type SchemaDescriptor struct {
	// Name is the PascalCase canonical form
	Name string `json:"-"`
	// Snake is the snake_case form
	Snake string `json:"-"`
	// Camel is the camelCase form
	Camel string `json:"-"`
	// Lower is the lowercase no-separator form used for fuzzy lookup
	Lower string `json:"-"`
	// Plural is the PascalCase plural form
	Plural string `json:"-"`
	// Table is the database table name
	Table string `json:"-"`
	// Label is the human-readable display label
	Label string `json:"-"`
}

// String returns the PascalCase canonical name
func (d SchemaDescriptor) String() string {
	return d.Name
}

// IsZero reports whether the descriptor is unset
func (d SchemaDescriptor) IsZero() bool {
	return d.Name == ""
}

// MarshalJSON serializes the descriptor as its snake_case form
func (d SchemaDescriptor) MarshalJSON() ([]byte, error) {
	return json.Marshal(d.Snake)
}

// UnmarshalJSON deserializes a descriptor from any known name variation
func (d *SchemaDescriptor) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}

	found, ok := LookupSchema(s)
	if !ok {
		return fmt.Errorf("%w: %s", ErrSchemaNotFound, s)
	}

	*d = found.SchemaDescriptor

	return nil
}

// EdgeDescriptor describes a linkable edge on a schema
type EdgeDescriptor struct {
	// Name is the edge name (e.g., "controls")
	Name string `json:"name"`
	// Target is the target schema
	Target *Schema `json:"target"`
	// Relationship is the edge relationship type ("M2M" or "O2M")
	Relationship string `json:"relationship"`
	// Link adds edges between the source entity and target entities
	Link func(ctx context.Context, client *generated.Client, entityID string, targetIDs ...string) error `json:"-"`
	// Unlink removes edges between the source entity and target entities
	Unlink func(ctx context.Context, client *generated.Client, entityID string, targetIDs ...string) error `json:"-"`
}

// TargetSelector specifies a set of entities to target via schema and expression
type TargetSelector struct {
	// Schema is the target entity schema
	Schema SchemaDescriptor `json:"schema"`
	// Expression is a CEL expression evaluated against each candidate entity
	Expression string `json:"expression"`
	// ExcludeIDs is a list of entity IDs to exclude from the result set
	ExcludeIDs []string `json:"exclude_ids,omitempty"`
}

// LinkSpec describes a linking operation between a source entity and matching targets
type LinkSpec struct {
	// Edge is the edge name on the source schema
	Edge string `json:"edge"`
	// Target specifies which entities to link via schema and expression
	Target TargetSelector `json:"target"`
}

// ExpressionEvaluator evaluates boolean expressions against entity data
type ExpressionEvaluator interface {
	// EvaluateBool evaluates the expression against the provided entity JSON and returns the result
	EvaluateBool(ctx context.Context, expression string, data json.RawMessage) (bool, error)
}
