// Code generated by entx CSV generator. DO NOT EDIT.
package {{ .PackageName }}
{{- if .EntPackage }}

import (
	"{{ .EntPackage }}"
)
{{- end }}

// CSVReferenceRule describes how a CSV column maps to a target ID field.
// All lookups are automatically scoped to the organization context from the request.
type CSVReferenceRule struct {
	// SourceColumn is the CSV column name containing friendly values
	SourceColumn string
	// TargetField is the Go field name on the input struct to populate
	TargetField string
	// TargetEntity is the entity type to query (e.g., User, Group)
	TargetEntity string
	// MatchField is the field on the target entity to match (e.g., email, name)
	MatchField string
	// IsSlice indicates if the target field is []string
	IsSlice bool
	// CreateIfMissing allows auto-creation during import
	CreateIfMissing bool
}

// CSVLookup represents a unique lookup type for resolving CSV values to IDs.
// All lookups are automatically scoped to the organization context from the request.
type CSVLookup struct {
	// TargetEntity is the entity type to query (e.g., User, Group)
	TargetEntity string
	// MatchField is the field to match on (e.g., email, name)
	MatchField string
	// CreateIfMissing indicates if this lookup supports auto-creation
	CreateIfMissing bool
}

// CSVSchemaInfo contains CSV reference metadata for a schema.
type CSVSchemaInfo struct {
	// SchemaName is the ent schema name
	SchemaName string
	// Rules contains the CSV reference rules for this schema
	Rules []CSVReferenceRule
}

// CSVReferenceRegistry maps schema names to their CSV reference info.
var CSVReferenceRegistry = map[string]CSVSchemaInfo{
{{- range $schema := .Schemas }}
	"{{ $schema.Name }}": {
		SchemaName: "{{ $schema.Name }}",
		Rules: []CSVReferenceRule{
{{- range $field := $schema.Fields }}
			{
				SourceColumn:    "{{ $field.CSVColumn }}",
				TargetField:     "{{ $field.GoFieldName }}",
				TargetEntity:    "{{ $field.TargetEntity }}",
				MatchField:      "{{ $field.MatchField }}",
				IsSlice:         {{ $field.IsSlice }},
				CreateIfMissing: {{ $field.CreateIfMissing }},
			},
{{- end }}
		},
	},
{{- end }}
}

// CSVLookups returns all unique lookup types used across schemas.
func CSVLookups() []CSVLookup {
	return []CSVLookup{
{{- range $lookup := .Lookups }}
		{
			TargetEntity:    "{{ $lookup.TargetEntity }}",
			MatchField:      "{{ $lookup.MatchField }}",
			CreateIfMissing: {{ $lookup.CreateIfMissing }},
		},
{{- end }}
	}
}

// GetCSVReferenceRules returns the CSV reference rules for a schema.
func GetCSVReferenceRules(schemaName string) []CSVReferenceRule {
	info, ok := CSVReferenceRegistry[schemaName]
	if !ok {
		return nil
	}

	return info.Rules
}

// HasCSVReferences returns true if a schema has CSV reference fields.
func HasCSVReferences(schemaName string) bool {
	info, ok := CSVReferenceRegistry[schemaName]
	return ok && len(info.Rules) > 0
}

// CSVColumnsBySchema returns a map of schema names to their CSV column names.
func CSVColumnsBySchema() map[string][]string {
	result := make(map[string][]string, len(CSVReferenceRegistry))
	for name, info := range CSVReferenceRegistry {
		columns := make([]string, 0, len(info.Rules))
		for _, rule := range info.Rules {
			columns = append(columns, rule.SourceColumn)
		}
		result[name] = columns
	}
	return result
}

{{- range $schema := .Schemas }}

// {{ $schema.Name }}CSVInput wraps Create{{ $schema.Name }}Input with CSV reference columns.
type {{ $schema.Name }}CSVInput struct {
{{- if $.EntPackage }}
	Input generated.Create{{ $schema.Name }}Input
{{- else }}
	// Input field requires EntPackage to be configured
	Input any
{{- end }}
{{- range $field := $schema.Fields }}
{{- if $field.IsSlice }}
	{{ $field.CSVColumn }} []string `csv:"{{ $field.CSVColumn }}"`
{{- else }}
	{{ $field.CSVColumn }} string `csv:"{{ $field.CSVColumn }}"`
{{- end }}
{{- end }}
}

// CSVInputWrapper marks {{ $schema.Name }}CSVInput for CSV header preprocessing.
func ({{ $schema.Name }}CSVInput) CSVInputWrapper() {}

// Get{{ $schema.Name }}CSVReferenceRules returns the CSV reference rules for {{ $schema.Name }}.
func Get{{ $schema.Name }}CSVReferenceRules() []CSVReferenceRule {
	return GetCSVReferenceRules("{{ $schema.Name }}")
}

// {{ $schema.Name }}CSVColumns returns the CSV column names for {{ $schema.Name }}.
func {{ $schema.Name }}CSVColumns() []string {
	return []string{
{{- range $field := $schema.Fields }}
		"{{ $field.CSVColumn }}",
{{- end }}
	}
}
{{- end }}
