// Code generated by entx/entityops. DO NOT EDIT.

package entityops

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"reflect"
	"slices"
	"strings"
	"sync"

	"entgo.io/ent/dialect/sql"
	"github.com/stoewer/go-strcase"

	generated "github.com/theopenlane/entx/vanilla/_example/ent"
	"github.com/theopenlane/entx/vanilla/_example/pkg/celx"
	"github.com/theopenlane/entx/vanilla/_example/pkg/jsonx"
	"github.com/theopenlane/entx/vanilla/_example/pkg/logx"
)

// EntityRef is a lightweight reference to an entity
type EntityRef struct {
	// ID is the entity identifier
	ID string
	// Schema is the entity's schema descriptor
	Schema SchemaDescriptor
}

// Schema is the runtime representation of a registered entity schema.
// It carries the schema identity and all supported operation closures.
type Schema struct {
	SchemaDescriptor
	// Create creates a new entity from a JSON input and returns the entity ID
	Create func(ctx context.Context, client *generated.Client, input json.RawMessage) (string, error)
	// Update applies a typed update input to an entity by ID
	Update func(ctx context.Context, client *generated.Client, entityID string, input json.RawMessage) error
	// Query returns all entities of this schema within an organization as JSON
	Query func(ctx context.Context, client *generated.Client, orgID string) ([]json.RawMessage, error)
	// QueryByKey returns entities of this schema within an organization whose given snake_case
	// field matches any of the provided values, pushing the predicate into the database
	QueryByKey func(ctx context.Context, client *generated.Client, orgID string, field string, values []string) ([]json.RawMessage, error)
	// Load loads a single entity by ID and returns its JSON representation
	Load func(ctx context.Context, client *generated.Client, entityID string) (json.RawMessage, error)
	// Fields is the unified field catalog for this schema, consumed by the workflow builder and the
	// integration cross-link config; workflow-eligible and match-key views are filtered from it
	Fields []FieldDescriptor
	// Edges lists every edge to an entityops schema (and workflow group edges) for this schema
	Edges []EdgeDescriptor
	// TaskRules are schema-level (unconditional) suggested-task rules declared via entx.SchemaTaskRule
	TaskRules []TaskRuleDescriptor
	// ProjectionType is the reflect.Type of this schema's flat CEL/jsonschema projection struct
	// ({Name}Projection); the registerable native-type view of the entity used for typed expressions
	ProjectionType reflect.Type
}

// applyClears rewrites explicit null values in a snake_case payload to the generated Clear<Field>
// flag so the field is cleared rather than ignored. Non-null keys pass through unchanged: they
// already match the create/update input's snake_case json tags, so no field re-keying is needed.
// The Clear<Field> name is derived by the same convention used for the @readOnly clear-field
// directive (Clear + UpperCamelCase of the snake field name)
func applyClears(raw json.RawMessage) json.RawMessage {
	if len(raw) == 0 {
		return raw
	}

	var m map[string]json.RawMessage
	if err := json.Unmarshal(raw, &m); err != nil {
		return raw
	}

	normalized := make(map[string]json.RawMessage, len(m))
	for k, v := range m {
		if isJSONNull(v) {
			normalized["Clear"+strcase.UpperCamelCase(k)] = json.RawMessage("true")
		} else {
			normalized[k] = v
		}
	}

	result, _ := json.Marshal(normalized)

	return result
}

// isJSONNull reports whether a raw JSON value is the literal null
func isJSONNull(raw json.RawMessage) bool {
	return bytes.Equal(bytes.TrimSpace(raw), []byte("null"))
}

// MatchKeyField reports whether field is a declared match-key column for this schema
func (s *Schema) MatchKeyField(field string) bool {
	for _, f := range s.Fields {
		if f.MatchKey && f.Name == field {
			return true
		}
	}

	return false
}

// EdgeByName returns the edge with the given name
func (s *Schema) EdgeByName(name string) (EdgeDescriptor, bool) {
	for _, e := range s.Edges {
		if e.Name == name {
			return e, true
		}
	}

	return EdgeDescriptor{}, false
}

// AllowedKey reports whether key is an integration mapping input key accepted for this schema
func (s *Schema) AllowedKey(key string) bool {
	for _, f := range s.Fields {
		if f.InputKey != "" && f.InputKey == key {
			return true
		}
	}

	return false
}

// matchKeyIn returns a selector predicate matching the given match-key column against any of values
func matchKeyIn(field string, values []string) func(*sql.Selector) {
	return func(s *sql.Selector) {
		args := make([]any, 0, len(values))
		for _, v := range values {
			args = append(args, v)
		}

		s.Where(sql.In(s.C(field), args...))
	}
}

// LookupField returns the schema's single ingest upsert lookup field. It returns false when the
// schema declares no lookup key or more than one, since priority between multiple lookup keys is
// schema-specific and stays with hand-written persistence
func (s *Schema) LookupField() (FieldDescriptor, bool) {
	var (
		found FieldDescriptor
		count int
	)

	for _, f := range s.Fields {
		if f.LookupKey {
			found = f
			count++
		}
	}

	return found, count == 1
}

// Upsert persists one create-input payload by the schema's lookup key: the payload's lookup value
// is matched against existing org-scoped records via the indexed key query, updating the single
// match or creating the record when none exists, and returns the entity id. Matching more than one
// record fails with ErrUpsertConflict rather than guessing. It composes the schema's catalog
// closures, so unlike Create/Update/QueryByKey it needs no per-schema wiring. Schemas whose lookup
// predicates are not a single org-scoped key column (integration-scoped lookups, multi-key
// priority) keep hand-written persistence instead
func (s *Schema) Upsert(ctx context.Context, client *generated.Client, ownerID string, payload json.RawMessage) (string, error) {
	ref := SchemaRef{Schema: s.Snake, Operation: OpUpsert}

	field, ok := s.LookupField()
	if !ok {
		return "", logError(ctx, ref, ErrUpsertUnsupported, fmt.Errorf("%s does not define exactly one lookup key", s.Name))
	}

	if s.Create == nil || s.Update == nil || s.QueryByKey == nil {
		return "", logError(ctx, ref, ErrUpsertUnsupported, fmt.Errorf("%s does not support catalog create, update, and key queries", s.Name))
	}

	value := lookupValue(payload, field.InputKey)
	if value == "" {
		return "", ErrUpsertKeyMissing
	}

	rows, err := s.QueryByKey(ctx, client, ownerID, field.Name, []string{value})
	if err != nil {
		return "", err
	}

	switch len(rows) {
	case 0:
		return s.Create(ctx, client, payload)
	case 1:
		id := entityID(rows[0])
		if id == "" {
			return "", logError(ctx, ref, ErrDecodeFailed, fmt.Errorf("%s row matching %s=%s has no id", s.Name, field.Name, value))
		}

		return id, s.Update(ctx, client, id, s.rekeyEdgesForUpdate(payload))
	default:
		return "", logError(ctx, ref, ErrUpsertConflict, fmt.Errorf("%s lookup %s=%s matched %d records", s.Name, field.Name, value, len(rows)))
	}
}

// rekeyEdgesForUpdate renames to-many edge keys in a create-input payload to their update-input add
// keys, so cross-object links injected at map time also apply on the re-ingest update path. Links
// are additive on update: edges carry no provenance, so targets no longer matched are never removed.
// Unique edge keys are shared between create and update inputs and pass through unchanged; keys for
// immutable edges have no update setter and are dropped by decode
func (s *Schema) rekeyEdgesForUpdate(payload json.RawMessage) json.RawMessage {
	var doc map[string]json.RawMessage
	if err := json.Unmarshal(payload, &doc); err != nil {
		return payload
	}

	changed := false

	for _, edge := range s.Edges {
		if edge.AddField == "" {
			continue
		}

		raw, ok := doc[edge.CreateField]
		if !ok {
			continue
		}

		doc[edge.AddField] = raw
		delete(doc, edge.CreateField)
		changed = true
	}

	if !changed {
		return payload
	}

	rekeyed, err := json.Marshal(doc)
	if err != nil {
		return payload
	}

	return rekeyed
}

// lookupValue extracts the string value of one create-input key from the payload
func lookupValue(payload json.RawMessage, key string) string {
	var doc map[string]json.RawMessage
	if err := json.Unmarshal(payload, &doc); err != nil {
		return ""
	}

	raw, ok := doc[key]
	if !ok {
		return ""
	}

	var value string
	if err := json.Unmarshal(raw, &value); err != nil {
		return ""
	}

	return strings.TrimSpace(value)
}

// entityID extracts the id column from one marshaled entity row
func entityID(row json.RawMessage) string {
	var decoded struct {
		ID string `json:"id"`
	}

	_ = json.Unmarshal(row, &decoded)

	return decoded.ID
}

// --- Per-schema registrations ---

var (
	SchemaOrganization = &Schema{
		SchemaDescriptor: SchemaDescriptor{
			Name:  "Organization",
			Snake: "organization",
			Camel: "organization",
			Lower: "organization",
		},
		ProjectionType: reflect.TypeFor[OrganizationProjection](),
		Create: func(ctx context.Context, client *generated.Client, input json.RawMessage) (string, error) {
			ref := SchemaRef{Schema: "organization", Operation: OpCreate}

			decoded, err := jsonx.Decode[generated.CreateOrganizationInput](input)
			if err != nil {
				return "", logError(ctx, ref, ErrDecodeFailed, err)
			}

			entity, err := client.Organization.Create().SetInput(decoded).Save(ctx)
			if err != nil {
				return "", logPersistError(ctx, ref, ErrCreateFailed, err)
			}

			return entity.ID, nil
		},
		Update: func(ctx context.Context, client *generated.Client, entityID string, input json.RawMessage) error {
			ref := SchemaRef{Schema: "organization", Operation: OpUpdate, EntityID: entityID}

			decoded, err := jsonx.Decode[generated.UpdateOrganizationInput](applyClears(input))
			if err != nil {
				return logError(ctx, ref, ErrDecodeFailed, err)
			}

			if err := client.Organization.UpdateOneID(entityID).SetInput(decoded).Exec(ctx); err != nil {
				return logPersistError(ctx, ref, ErrUpdateFailed, err)
			}

			return nil
		},
		Load: func(ctx context.Context, client *generated.Client, entityID string) (json.RawMessage, error) {
			ref := SchemaRef{Schema: "organization", Operation: OpLoad, EntityID: entityID}

			entity, err := client.Organization.Get(ctx, entityID)
			if err != nil {
				return nil, logError(ctx, ref, ErrLoadFailed, err)
			}

			data, err := json.Marshal(entity)
			if err != nil {
				return nil, logError(ctx, ref, ErrMarshalFailed, err)
			}

			return data, nil
		},
	}
	SchemaWorkflowInstance = &Schema{
		SchemaDescriptor: SchemaDescriptor{
			Name:  "WorkflowInstance",
			Snake: "workflow_instance",
			Camel: "workflowInstance",
			Lower: "workflowinstance",
		},
		ProjectionType: reflect.TypeFor[WorkflowInstanceProjection](),
		Load: func(ctx context.Context, client *generated.Client, entityID string) (json.RawMessage, error) {
			ref := SchemaRef{Schema: "workflow_instance", Operation: OpLoad, EntityID: entityID}

			entity, err := client.WorkflowInstance.Get(ctx, entityID)
			if err != nil {
				return nil, logError(ctx, ref, ErrLoadFailed, err)
			}

			data, err := json.Marshal(entity)
			if err != nil {
				return nil, logError(ctx, ref, ErrMarshalFailed, err)
			}

			return data, nil
		},
	}
	SchemaWorkflowObjectRef = &Schema{
		SchemaDescriptor: SchemaDescriptor{
			Name:  "WorkflowObjectRef",
			Snake: "workflow_object_ref",
			Camel: "workflowObjectRef",
			Lower: "workflowobjectref",
		},
		ProjectionType: reflect.TypeFor[WorkflowObjectRefProjection](),
		Load: func(ctx context.Context, client *generated.Client, entityID string) (json.RawMessage, error) {
			ref := SchemaRef{Schema: "workflow_object_ref", Operation: OpLoad, EntityID: entityID}

			entity, err := client.WorkflowObjectRef.Get(ctx, entityID)
			if err != nil {
				return nil, logError(ctx, ref, ErrLoadFailed, err)
			}

			data, err := json.Marshal(entity)
			if err != nil {
				return nil, logError(ctx, ref, ErrMarshalFailed, err)
			}

			return data, nil
		},
	}
)

// init wires cross-schema edge references after all Schema vars are initialized
func init() {
	SchemaOrganization.Fields = []FieldDescriptor{
		{Name: "created_at", Label: "CreatedAt", Type: "time.Time"},
		{Name: "created_by", Label: "CreatedBy", Type: "string", MatchKey: true},
		{Name: "description", Label: "Description", Type: "string", MatchKey: true},
		{Name: "display_id", Label: "DisplayID", Type: "string", MatchKey: true},
		{Name: "name", Label: "Name", Type: "string", MatchKey: true},
		{Name: "preferences", Label: "Preferences", Type: "map[string]interface {}", TaskRules: []TaskRuleDescriptor{{RuleID: "import-existing-policies", Expression: "value.policies.has_existing == true", Trigger: "createOnly"}, {RuleID: "framework", EachElement: "value.frameworks"}}},
		{Name: "updated_at", Label: "UpdatedAt", Type: "time.Time"},
		{Name: "updated_by", Label: "UpdatedBy", Type: "string", MatchKey: true},
	}
	SchemaWorkflowInstance.Fields = []FieldDescriptor{
		{Name: "status", Label: "Status", Type: "string", WorkflowEligible: true, MatchKey: true},
	}
	SchemaWorkflowObjectRef.Fields = []FieldDescriptor{
		{Name: "organization_id", Label: "OrganizationID", Type: "string", MatchKey: true},
		{Name: "workflow_instance_id", Label: "WorkflowInstanceID", Type: "string", MatchKey: true},
	}
	SchemaOrganization.TaskRules = []TaskRuleDescriptor{
		{RuleID: "setup-payment-method"},
	}
	SchemaWorkflowObjectRef.Edges = []EdgeDescriptor{
		{
			Name:             "organization",
			Label:            "Organization",
			Target:           SchemaOrganization,
			TargetType:       "Organization",
			Immutable:        true,
			Unique:           true,
			CreateField:      "organization_id",
			Field:            "organization_id",
			WorkflowEligible: true,
		},
		{
			Name:        "workflow_instance",
			Label:       "WorkflowInstance",
			Target:      SchemaWorkflowInstance,
			TargetType:  "WorkflowInstance",
			Immutable:   true,
			Unique:      true,
			CreateField: "workflow_instance_id",
			Field:       "workflow_instance_id",
		},
	}

	// through edges are linked by creating join entity rows — one per target, each with its own
	// generated id — so wrap the create and update closures of schemas that have them: through-edge
	// id lists are split out of the payload and applied as rows after the mutation succeeds
	for _, s := range allSchemas {
		if !slices.ContainsFunc(s.Edges, func(e EdgeDescriptor) bool { return e.Through }) {
			continue
		}

		schema := s

		if create := schema.Create; create != nil {
			schema.Create = func(ctx context.Context, client *generated.Client, input json.RawMessage) (string, error) {
				input, throughIDs := splitThroughEdgeIDs(schema, input)

				id, err := create(ctx, client, input)
				if err != nil {
					return id, err
				}

				return id, applyThroughEdgeIDs(ctx, client, schema, id, throughIDs)
			}
		}

		if update := schema.Update; update != nil {
			schema.Update = func(ctx context.Context, client *generated.Client, entityID string, input json.RawMessage) error {
				input, throughIDs := splitThroughEdgeIDs(schema, input)

				if err := update(ctx, client, entityID, input); err != nil {
					return err
				}

				return applyThroughEdgeIDs(ctx, client, schema, entityID, throughIDs)
			}
		}
	}
}

// splitThroughEdgeIDs removes through-edge id lists from a create or update payload, returning the
// cleaned payload and the target ids per edge name. Malformed values are left in place so input
// validation rejects them instead of being silently discarded
func splitThroughEdgeIDs(s *Schema, payload json.RawMessage) (json.RawMessage, map[string][]string) {
	var doc map[string]json.RawMessage
	if err := json.Unmarshal(payload, &doc); err != nil {
		return payload, nil
	}

	var ids map[string][]string

	for _, edge := range s.Edges {
		if !edge.Through {
			continue
		}

		raw, ok := doc[edge.CreateField]
		if !ok {
			continue
		}

		var targetIDs []string
		if err := json.Unmarshal(raw, &targetIDs); err != nil {
			continue
		}

		if ids == nil {
			ids = map[string][]string{}
		}

		ids[edge.Name] = targetIDs
		delete(doc, edge.CreateField)
	}

	if ids == nil {
		return payload, nil
	}

	cleaned, err := json.Marshal(doc)
	if err != nil {
		return payload, nil
	}

	return cleaned, ids
}

// applyThroughEdgeIDs creates the join entity rows for each split through edge
func applyThroughEdgeIDs(ctx context.Context, client *generated.Client, s *Schema, sourceID string, ids map[string][]string) error {
	for name, targetIDs := range ids {
		edge, ok := s.EdgeByName(name)
		if !ok || edge.LinkThrough == nil || len(targetIDs) == 0 {
			continue
		}

		if err := edge.LinkThrough(ctx, client, sourceID, targetIDs); err != nil {
			return logError(ctx, SchemaRef{Schema: s.Snake, Operation: OpLink, EntityID: sourceID, Edge: name}, ErrLinkFailed, err)
		}
	}

	return nil
}

// --- Lookup registry ---

var allSchemas = []*Schema{
	SchemaOrganization,
	SchemaWorkflowInstance,
	SchemaWorkflowObjectRef,
}

var (
	schemaLookupOnce sync.Once
	schemaLookupMap  map[string]*Schema
)

func buildSchemaLookup() {
	schemaLookupOnce.Do(func() {
		schemaLookupMap = make(map[string]*Schema, len(allSchemas)*4)

		for _, s := range allSchemas {
			schemaLookupMap[s.Name] = s
			schemaLookupMap[s.Snake] = s
			schemaLookupMap[s.Camel] = s
			schemaLookupMap[s.Lower] = s
		}
	})
}

// LookupSchema resolves a schema by any known name variation (PascalCase, snake_case,
// camelCase, or lowercase). Returns the schema and whether a match was found.
func LookupSchema(name string) (*Schema, bool) {
	buildSchemaLookup()

	if s, ok := schemaLookupMap[name]; ok {
		return s, true
	}

	normalized := strings.ToLower(strings.NewReplacer("_", "", "-", "", " ", "").Replace(name))

	if s, ok := schemaLookupMap[normalized]; ok {
		return s, true
	}

	return nil, false
}

// AllSchemas returns a copy of all registered schemas
func AllSchemas() []*Schema {
	result := make([]*Schema, len(allSchemas))
	copy(result, allSchemas)

	return result
}

// SelectTargets queries entities matching a target selector and filters them with a typed CEL
// evaluator bound to the target schema's native projection — and, when the selector carries
// SourceContext with a SourceSchema, the source schema's projection as "source" — so selector
// expressions resolve typed fields rather than evaluating against a map[string]any
func SelectTargets(ctx context.Context, client *generated.Client, orgID string, selector TargetSelector) ([]EntityRef, error) {
	schema, ok := LookupSchema(selector.Schema.Name)
	if !ok {
		return nil, logError(ctx, SchemaRef{Schema: selector.Schema.Snake, Operation: OpQuery}, ErrSchemaNotFound, fmt.Errorf("schema %s is not registered", selector.Schema.Name))
	}

	entities, err := selectCandidates(ctx, client, schema, orgID, selector)
	if err != nil {
		return nil, err
	}

	var (
		eval      *celx.NativeEntityEvaluator
		useSource bool
	)

	if selector.Expression != "" {
		var sourceType reflect.Type

		if len(selector.SourceContext) > 0 && !selector.SourceSchema.IsZero() {
			if src, ok := LookupSchema(selector.SourceSchema.Name); ok && src.ProjectionType != nil {
				sourceType = src.ProjectionType
				useSource = true
			}
		}

		envCfg := celx.StrictEnvConfig()
		envCfg.CrossTypeNumericComparisons = true

		eval, err = celx.NewNativeEntityEvaluator(envCfg, celx.FastEvalConfig(), schema.ProjectionType, sourceType)
		if err != nil {
			errorEvent(ctx, SchemaRef{Schema: schema.Snake, Operation: OpQuery}, err).Str(FieldExpression, selector.Expression).Msg(ErrEvaluatorBuildFailed.Error())

			return nil, fmt.Errorf("%w: %w", ErrEvaluatorBuildFailed, err)
		}

		logx.FromContext(ctx).Debug().Str(FieldSchema, schema.Snake).Str(FieldExpression, selector.Expression).Int("candidates", len(entities)).Msg("entityops: filtering targets with expression")
	}

	excludeSet := make(map[string]struct{}, len(selector.ExcludeIDs))
	for _, id := range selector.ExcludeIDs {
		excludeSet[id] = struct{}{}
	}

	ref := SchemaRef{Schema: schema.Snake, Operation: OpQuery}
	var results []EntityRef

	for _, data := range entities {
		var parsed struct {
			ID string `json:"id"`
		}

		if err := json.Unmarshal(data, &parsed); err != nil {
			logError(ctx, ref, ErrDecodeFailed, err)
			continue
		}

		if _, excluded := excludeSet[parsed.ID]; excluded {
			continue
		}

		if selector.Expression != "" {
			var (
				match   bool
				evalErr error
			)

			if useSource {
				match, evalErr = eval.EvaluateBoolWithSource(ctx, selector.Expression, data, selector.SourceContext)
			} else {
				match, evalErr = eval.EvaluateBool(ctx, selector.Expression, data)
			}

			if evalErr != nil {
				errorEvent(ctx, SchemaRef{Schema: schema.Snake, Operation: OpQuery, EntityID: parsed.ID}, evalErr).Str(FieldExpression, selector.Expression).Msg(ErrEvaluationFailed.Error())
				continue
			}

			if !match {
				continue
			}
		}

		results = append(results, EntityRef{ID: parsed.ID, Schema: schema.SchemaDescriptor})
	}

	return results, nil
}

// selectCandidates resolves the candidate entity set for a target selector. When the selector
// carries a KeyMatch it issues an indexed query that pushes the key predicate into the database;
// otherwise it loads all org-scoped entities for row-by-row expression evaluation
func selectCandidates(ctx context.Context, client *generated.Client, schema *Schema, orgID string, selector TargetSelector) ([]json.RawMessage, error) {
	if selector.KeyMatch != nil {
		if schema.QueryByKey == nil {
			return nil, fmt.Errorf("%w: %s", ErrKeyMatchUnsupported, schema.Name)
		}

		values := collectKeyValues(selector.SourceContext, selector.KeyMatch)
		if len(values) == 0 {
			return nil, nil
		}

		return schema.QueryByKey(ctx, client, orgID, selector.KeyMatch.TargetField, values)
	}

	if schema.Query == nil {
		return nil, fmt.Errorf("%w: %s", ErrQueryUnsupported, schema.Name)
	}

	return schema.Query(ctx, client, orgID)
}

// collectKeyValues extracts the deduplicated, non-empty source-side key values for a KeyMatch
// from the source entity JSON, combining the scalar SourceField with the SourceList values
func collectKeyValues(sourceContext json.RawMessage, km *KeyMatch) []string {
	if len(sourceContext) == 0 {
		return nil
	}

	var raw map[string]json.RawMessage
	if err := json.Unmarshal(sourceContext, &raw); err != nil {
		return nil
	}

	seen := make(map[string]struct{})
	var values []string

	add := func(s string) {
		if s == "" {
			return
		}

		if _, ok := seen[s]; ok {
			return
		}

		seen[s] = struct{}{}
		values = append(values, s)
	}

	if km.SourceField != "" {
		if v, ok := raw[km.SourceField]; ok {
			var s string
			if json.Unmarshal(v, &s) == nil {
				add(s)
			}
		}
	}

	if km.SourceList != "" {
		if v, ok := raw[km.SourceList]; ok {
			var list []string
			if json.Unmarshal(v, &list) == nil {
				for _, s := range list {
					add(s)
				}
			}
		}
	}

	return values
}
