// Code generated by entx/entityops. DO NOT EDIT.

package entityops

import (
	mapx ""
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"reflect"
	"slices"
	"strconv"
	"strings"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/samber/lo"
	"github.com/stoewer/go-strcase"
	"github.com/theopenlane/utils/contextx"

	generated "github.com/theopenlane/entx/vanilla/_example/ent"
	"github.com/theopenlane/entx/vanilla/_example/pkg/celx"
	"github.com/theopenlane/entx/vanilla/_example/pkg/gala"
	"github.com/theopenlane/entx/vanilla/_example/pkg/jsonx"
	"github.com/theopenlane/entx/vanilla/_example/pkg/logx"
)

// entityRef is a lightweight reference to an entity
type entityRef struct {
	// ID is the entity identifier
	ID string
	// Schema is the entity's schema descriptor
	Schema SchemaDescriptor
}

// IngestRequest is the durable schema-ingest command. Defaults are resolved through the schema
// field catalog, so operation-specific values do not become fields on the ingest machinery.
type IngestRequest struct {
	OperationContext gala.OperationContext `json:"operationContext"`
	Input            json.RawMessage       `json:"input"`
	ThroughEdgeIDs   map[string][]string   `json:"throughEdgeIds,omitempty"`
	Defaults         map[string]any        `json:"defaults,omitempty"`
	Links            []LinkSpec            `json:"links,omitempty"`
	// RunID is the integration run the record belongs to
	RunID string `json:"runId,omitempty"`
}

// IngestIntegrationResolver loads the integration referenced by the durable operation context.
// The application owns terminal-error classification for integrations removed while work is queued.
type IngestIntegrationResolver func(context.Context, *generated.Client, gala.OperationContext) (*generated.Integration, error)

// IngestPersist is the type-erased persistence operation bound to a schema at startup.
type IngestPersist func(context.Context, *generated.Client, *generated.Integration, json.RawMessage) (id string, changed bool, managed bool, err error)

// IngestCapability is the schema's single asynchronous ingest control surface.
type IngestCapability struct {
	Topic   gala.Topic[IngestRequest]
	prepare func(context.Context, *generated.Integration, json.RawMessage) (json.RawMessage, error)
	persist IngestPersist
	// buildUpdate binds the ingest payload as an update mutation and returns it with its save closure
	buildUpdate func(context.Context, *generated.Client, json.RawMessage, json.RawMessage) (ent.Mutation, func(context.Context) error, error)
}

// Schema is the runtime representation of a registered entity schema. It carries the schema
// identity and its operation closures. Load, Fields, and Edges are universal; the remaining
// closures are emitted only for schemas whose capabilities can reach them and are nil otherwise
type Schema struct {
	SchemaDescriptor
	// Create creates a new entity from a JSON input and returns the entity ID; emitted only for
	// integration-mapped schemas, whose ingest upsert is the sole caller
	Create func(ctx context.Context, client *generated.Client, input json.RawMessage) (string, error)
	// Update applies a typed update input to an entity by ID; emitted only for integration-mapped
	// and workflow-eligible schemas
	Update func(ctx context.Context, client *generated.Client, entityID string, input json.RawMessage) error
	// Query returns all entities of this schema within an organization as JSON; emitted only for
	// integration-mapped schemas and link-rule targets, whose target selection is the sole caller
	Query func(ctx context.Context, client *generated.Client, orgID string) ([]json.RawMessage, error)
	// QueryByKey returns entities of this schema within an organization whose given snake_case
	// field matches any of the provided values, pushing the predicate into the database; emitted
	// only for integration-mapped schemas and link-rule targets with match-key columns
	QueryByKey func(ctx context.Context, client *generated.Client, orgID string, field string, values []string) ([]json.RawMessage, error)
	// IntegrationFKField is the schema's mutable FK column to Integration, if any
	IntegrationFKField string
	// IntegrationM2MEdge is the name of the schema's to-many edge to Integration, if any
	IntegrationM2MEdge string
	// IntegrationRunM2MEdge is the name of the schema's to-many edge to IntegrationRun, if any
	IntegrationRunM2MEdge string
	// RemovedAtField is the snake_case name of the schema's SnapshotRemoval-annotated field, if any
	RemovedAtField string
	// RemovedAtEpisodic reports whether removal is a recurring observation rather than a permanent tombstone
	RemovedAtEpisodic bool
	// Lookup lists the schema's composite ingest lookup alternatives in order
	Lookup []LookupAlternative
	// InstanceScoped reports whether same-key records from different source instances are distinct rows
	InstanceScoped bool
	// QueryByLookup returns rows matching one of the given key tuples for a declared lookup alternative
	QueryByLookup func(ctx context.Context, client *generated.Client, ownerID string, alternative int, keys []LookupValues) ([]json.RawMessage, error)
	// SnapshotScope returns the non-removed rows one installation manages for a definition and instance
	SnapshotScope func(ctx context.Context, client *generated.Client, ownerID, definitionID, instanceID, managedBy string) ([]json.RawMessage, error)
	// MarkRemoved bulk-marks the given ids removed at the given time under the given integration run
	MarkRemoved func(ctx context.Context, client *generated.Client, ids []string, at time.Time, runID string) error
	// FillProvenance fills missing provenance on rows linked to the installation and reports rows written
	FillProvenance func(ctx context.Context, client *generated.Client, installation *generated.Integration) (int, error)
	// Load loads a single entity by ID and returns its JSON representation
	Load func(ctx context.Context, client *generated.Client, entityID string) (json.RawMessage, error)
	// LoadObject loads the native generated Ent object for consumers that require its interfaces;
	// emitted only for workflow-eligible schemas, whose workflow object loading is the sole caller
	LoadObject func(ctx context.Context, client *generated.Client, entityID string) (any, error)
	// Fields is the unified field catalog for this schema, consumed by the workflow builder and the
	// integration cross-link config; workflow-eligible and match-key views are filtered from it
	Fields []FieldDescriptor
	// Edges lists every edge to an entityops schema (and workflow group edges) for this schema
	Edges []EdgeDescriptor
	// TaskRules are schema-level (unconditional) suggested-task rules declared via entx.SchemaTaskRule
	TaskRules []TaskRuleDescriptor
	// ProjectionType is the reflect.Type of this schema's flat CEL/jsonschema projection struct
	// ({Name}Projection); the registerable native-type view of the entity used for typed expressions.
	// Projections are emitted only for integration-mapped, workflow-eligible, and link-target
	// schemas, the schemas typed expression evaluation can reach; nil otherwise
	ProjectionType reflect.Type
	// Ingest is present when this schema supports mapped integration ingestion
	Ingest *IngestCapability
	// ConsoleRoute is present only when the schema explicitly declares a console route
	ConsoleRoute *ConsoleRoute
	// MentionSpec is present only when the schema explicitly declares mention scanning
	MentionSpec *MentionSpec
	// ApprovalSpec is present only when the schema explicitly declares approval fields
	ApprovalSpec *ApprovalSpec
}

// defaultIngestPersist returns the stock upsert-backed persistence for an ingest schema
func defaultIngestPersist(s *Schema) IngestPersist {
	return func(ctx context.Context, client *generated.Client, integration *generated.Integration, payload json.RawMessage) (string, bool, bool, error) {
		owner := lookupValue(payload, FieldOwnerID)
		if owner == "" && integration != nil {
			owner = integration.OwnerID
		}

		return s.Upsert(ctx, client, owner, payload)
	}
}

// registerIngest attaches the schema's durable ingest consumer.
func (s *Schema) registerIngest(runtime *gala.Gala, resolveIntegration IngestIntegrationResolver) error {
	if s == nil || s.Ingest == nil || s.Ingest.prepare == nil {
		return ErrIngestUnsupported
	}

	if resolveIntegration == nil {
		return fmt.Errorf("%w: %s registered without an integration resolver", ErrIngestMisconfigured, s.Name)
	}

	if s.Ingest.persist == nil {
		return fmt.Errorf("%w: %s registered before persistence was bound", ErrIngestMisconfigured, s.Name)
	}

	_, err := gala.Register(runtime, gala.Definition[IngestRequest]{
		Topic: s.Ingest.Topic,
		Name:  s.Name + ".ingest",
		Handle: func(handlerCtx gala.HandlerContext, request IngestRequest) error {
			client := generated.FromContext(handlerCtx.Context)
			if client == nil {
				return logError(handlerCtx.Context, SchemaRef{Schema: s.Snake, Operation: refOpCreate}, ErrClientResolveFailed, fmt.Errorf("ent client missing from restored handler context"))
			}

			return s.handleIngest(handlerCtx.Context, client, resolveIntegration, request)
		},
	})
	if err != nil {
		return fmt.Errorf("%w: %w", ErrListenerRegistrationFailed, err)
	}

	return nil
}

// RegisterIngestListeners attaches every generated schema-ingest consumer.
func RegisterIngestListeners(runtime *gala.Gala, resolveIntegration IngestIntegrationResolver) error {
	for _, schema := range allSchemas {
		if schema.Ingest == nil {
			continue
		}

		if err := schema.registerIngest(runtime, resolveIntegration); err != nil {
			return err
		}
	}

	return nil
}

// EmitIngest queues one durable schema-ingest command.
func (s *Schema) EmitIngest(ctx context.Context, runtime *gala.Gala, headers gala.Headers, request IngestRequest) error {
	if s == nil || s.Ingest == nil {
		return ErrIngestUnsupported
	}

	ref := SchemaRef{Schema: s.Snake, Operation: refOpEmit}
	if len(headers.Metadata) == 0 {
		metadata, err := json.Marshal(request.OperationContext)
		if err != nil {
			return logError(ctx, ref, ErrMarshalFailed, err)
		}

		headers.Metadata = metadata
	}

	ctx = gala.WithOperationContext(ctx, request.OperationContext)

	if _, err := runtime.EmitWithHeaders(ctx, s.Ingest.Topic.Name, request, headers); err != nil {
		return logError(ctx, ref, ErrEmitFailed, err)
	}

	return nil
}

// PersistIngest prepares and persists one mapped record synchronously through the schema's bound
// persistence, sharing the preparation the durable ingest consumer applies
func (s *Schema) PersistIngest(ctx context.Context, client *generated.Client, integration *generated.Integration, payload json.RawMessage) (id string, changed bool, managed bool, err error) {
	if s == nil || s.Ingest == nil {
		return "", false, false, ErrIngestUnsupported
	}

	if s.Ingest.persist == nil {
		return "", false, false, fmt.Errorf("%w: %s persistence not bound", ErrIngestMisconfigured, s.Name)
	}

	// the split runs before prepare: prepare round-trips the payload through the typed create
	// input, which drops through-edge keys the input struct cannot carry
	payload, throughIDs := splitThroughEdgeIDs(s, payload)

	payload, err = s.Ingest.prepare(ctx, integration, payload)
	if err != nil {
		return "", false, false, err
	}

	id, changed, managed, err = s.Ingest.persist(ctx, client, integration, payload)
	if err != nil {
		return id, changed, managed, err
	}

	if !managed {
		return id, false, false, nil
	}

	return id, changed, managed, applyThroughEdgeIDs(ctx, client, s, id, throughIDs)
}

// logSanitizedIngestField records one optional mapped field dropped by ingest preparation because
// its value failed the schema's field validation
func logSanitizedIngestField(ctx context.Context, schema, field string, err error) {
	logx.FromContext(ctx).Warn().Err(err).Str(FieldSchema, schema).Str("field", field).Msg("entityops: dropped invalid optional ingest field")
}

// handleIngest runs the mandatory consumer-side pipeline for one queued mapped entity.
func (s *Schema) handleIngest(ctx context.Context, client *generated.Client, resolve IngestIntegrationResolver, request IngestRequest) error {
	ref := SchemaRef{Schema: s.Snake, Operation: refOpCreate}
	ctx = gala.WithOperationContext(ctx, request.OperationContext)

	integration, err := resolve(ctx, client, request.OperationContext)
	if err != nil {
		return logError(ctx, ref, ErrIngestIntegrationResolveFailed, err)
	}

	payload, err := applyIngestDefaults(s, request.Input, request.Defaults)
	if err != nil {
		return err
	}

	payload = StampProvenance(payload, s, integration, request.RunID)

	payload, err = s.Ingest.prepare(ctx, integration, payload)
	if err != nil {
		return err
	}

	ownerID := request.OperationContext.OwnerID
	if ownerID == "" && integration != nil {
		ownerID = integration.OwnerID
	}

	payload, err = InjectCreateLinks(ctx, client, ownerID, s, payload, request.Links)
	if err != nil {
		return err
	}

	payload, throughIDs := splitThroughEdgeIDs(s, payload)
	if len(request.ThroughEdgeIDs) > 0 && throughIDs == nil {
		throughIDs = make(map[string][]string, len(request.ThroughEdgeIDs))
	}

	for edge, ids := range request.ThroughEdgeIDs {
		throughIDs[edge] = append(throughIDs[edge], ids...)
	}

	id, _, managed, err := s.Ingest.persist(ctx, client, integration, payload)
	if errors.Is(err, ErrUpsertStaleRun) {
		return nil
	}

	if err != nil {
		return logPersistError(ctx, ref, ErrPersistFailed, err)
	}

	if !managed {
		return nil
	}

	if err := applyThroughEdgeIDs(ctx, client, s, id, throughIDs); err != nil {
		return logPersistError(ctx, ref, ErrPersistFailed, err)
	}

	return nil
}

// applyIngestDefaults applies caller-supplied defaults through canonical schema field names. An
// explicit non-zero mapped value wins over a default.
func applyIngestDefaults(schema *Schema, payload json.RawMessage, defaults map[string]any) (json.RawMessage, error) {
	if len(defaults) == 0 {
		return payload, nil
	}

	document, err := jsonx.ToRawMap(payload)
	if err != nil {
		return nil, fmt.Errorf("%w: %w", ErrDecodeFailed, err)
	}

	for name, value := range defaults {
		field, ok := schema.FieldByName(name)
		if !ok {
			return nil, fmt.Errorf("%w: %s.%s", ErrFieldNotFound, schema.Snake, name)
		}

		key := field.InputKey
		if key == "" {
			key = field.Name
		}

		if existing, ok := document[key]; ok && !isDefaultableJSON(existing) {
			continue
		}

		raw, err := json.Marshal(value)
		if err != nil {
			return nil, fmt.Errorf("%w: %s.%s: %w", ErrMarshalFailed, schema.Snake, name, err)
		}

		document[key] = raw
	}

	prepared, err := json.Marshal(document)
	if err != nil {
		return nil, fmt.Errorf("%w: %w", ErrMarshalFailed, err)
	}

	return prepared, nil
}

// isDefaultableJSON reports whether a mapped JSON value is absent in the semantic sense used by
// ingest defaults. False and numeric zero remain explicit caller values.
func isDefaultableJSON(raw json.RawMessage) bool {
	return jsonx.IsEmptyRawMessage(raw) || bytes.Equal(bytes.TrimSpace(raw), []byte(`""`))
}

// applyClears rewrites explicit null values in a snake_case payload to the generated Clear<Field>
// flag so the field is cleared rather than ignored. Non-null keys pass through unchanged: they
// already match the create/update input's snake_case json tags, so no field re-keying is needed.
// The Clear<Field> name is derived by the same convention used for the @readOnly clear-field
// directive (Clear + UpperCamelCase of the snake field name)
func applyClears(raw json.RawMessage) json.RawMessage {
	return jsonx.EditObject(raw, func(doc map[string]json.RawMessage) bool {
		changed := false

		for key, value := range doc {
			if jsonx.IsEmptyRawMessage(value) {
				delete(doc, key)
				doc["Clear"+strcase.UpperCamelCase(key)] = json.RawMessage("true")
				changed = true
			}
		}

		return changed
	})
}

// softDeleteFieldName is the column the soft-delete mixin adds to participating schemas
const softDeleteFieldName = "deleted_at"

// SoftDeletes reports whether this schema soft-deletes rows via the deleted_at column
func (s *Schema) SoftDeletes() bool {
	for _, f := range s.Fields {
		if f.Name == softDeleteFieldName {
			return true
		}
	}

	return false
}

// MatchKeyField reports whether field is a declared match-key column for this schema
func (s *Schema) MatchKeyField(field string) bool {
	if field == "id" {
		return true
	}
	for _, f := range s.Fields {
		if f.MatchKey && f.Name == field {
			return true
		}
	}

	return false
}

// EdgeByName returns the edge with the given name
func (s *Schema) EdgeByName(name string) (EdgeDescriptor, bool) {
	for _, e := range s.Edges {
		if e.Name == name {
			return e, true
		}
	}

	return EdgeDescriptor{}, false
}

// ResolveInputKey resolves a caller-supplied field name to this schema's canonical create-input
// key. It accepts the mapping input key, the snake_case field name, or case variants of either;
// annotation-declared input keys win over raw field names. The returned key matches the create
// input's snake_case json tags so mapped payloads unmarshal without re-keying
func (s *Schema) ResolveInputKey(name string) (string, bool) {
	name = strings.TrimSpace(name)
	if name == "" {
		return "", false
	}

	for _, f := range s.Fields {
		if f.InputKey != "" && strings.EqualFold(f.InputKey, name) {
			return f.InputKey, true
		}
	}

	snake := strcase.SnakeCase(name)

	for _, f := range s.Fields {
		if f.Name != snake && !strings.EqualFold(f.Name, name) {
			continue
		}

		if f.InputKey != "" {
			return f.InputKey, true
		}

		return f.Name, true
	}

	return "", false
}

// FieldByName returns the field descriptor addressed by a caller-supplied field or input name.
func (s *Schema) FieldByName(name string) (FieldDescriptor, bool) {
	key, ok := s.ResolveInputKey(name)
	if !ok {
		return FieldDescriptor{}, false
	}

	for _, f := range s.Fields {
		if f.InputKey == key || f.Name == key {
			return f, true
		}
	}

	return FieldDescriptor{}, false
}

// CoerceValue coerces a raw document value into the Go shape of the named field per its catalog
// type. Unknown and custom field types pass through unchanged so JSON unmarshalling into the
// typed create input remains the final arbiter
func (s *Schema) CoerceValue(name string, value any) (any, error) {
	field, ok := s.FieldByName(name)
	if !ok {
		return nil, fmt.Errorf("%w: %s.%s", ErrFieldNotFound, s.Snake, name)
	}

	switch field.Type {
	case "string":
		return coerceString(value), nil
	case "bool":
		return coerceBool(value)
	case "int", "int8", "int16", "int32", "int64", "uint", "uint8", "uint16", "uint32", "uint64", "float32", "float64":
		return coerceFloat(value)
	case "[]string":
		return coerceStringSlice(value), nil
	case "time.Time", "models.DateTime":
		// models.DateTime unmarshals the same RFC3339/date-only layouts coerceTime parses
		return coerceTime(value)
	default:
		return value, nil
	}
}

// coerceString renders a scalar value as its string form
func coerceString(value any) string {
	switch v := value.(type) {
	case string:
		return v
	case fmt.Stringer:
		return v.String()
	case bool:
		return strconv.FormatBool(v)
	case float64:
		return strconv.FormatFloat(v, 'f', -1, 64)
	case float32:
		return strconv.FormatFloat(float64(v), 'f', -1, 32)
	case int:
		return strconv.Itoa(v)
	case int64:
		return strconv.FormatInt(v, 10)
	default:
		return fmt.Sprintf("%v", value)
	}
}

// coerceBool parses a boolean from native and common string forms
func coerceBool(value any) (bool, error) {
	switch v := value.(type) {
	case bool:
		return v, nil
	case string:
		switch strings.ToLower(strings.TrimSpace(v)) {
		case "true", "yes", "y", "1":
			return true, nil
		case "false", "no", "n", "0":
			return false, nil
		}
	}

	return false, fmt.Errorf("%w: bool from %T", ErrValueCoercion, value)
}

// coerceFloat parses a numeric value from native numeric types or a string form
func coerceFloat(value any) (float64, error) {
	switch v := value.(type) {
	case float64:
		return v, nil
	case float32:
		return float64(v), nil
	case int:
		return float64(v), nil
	case int64:
		return float64(v), nil
	case string:
		parsed, err := strconv.ParseFloat(strings.TrimSpace(v), 64)
		if err != nil {
			return 0, fmt.Errorf("%w: number from %q", ErrValueCoercion, v)
		}

		return parsed, nil
	default:
		return 0, fmt.Errorf("%w: number from %T", ErrValueCoercion, value)
	}
}

// coerceStringSlice renders a value as a slice of trimmed non-empty strings
func coerceStringSlice(value any) []string {
	switch v := value.(type) {
	case []string:
		return v
	case []any:
		values := make([]string, 0, len(v))
		for _, item := range v {
			s := strings.TrimSpace(coerceString(item))
			if s != "" {
				values = append(values, s)
			}
		}

		return values
	default:
		s := strings.TrimSpace(coerceString(value))
		if s == "" {
			return nil
		}

		return []string{s}
	}
}

// coerceTime parses a timestamp from native time or RFC3339/date-only string forms
func coerceTime(value any) (time.Time, error) {
	switch v := value.(type) {
	case time.Time:
		return v, nil
	case string:
		trimmed := strings.TrimSpace(v)

		parsed, err := time.Parse(time.RFC3339, trimmed)
		if err == nil {
			return parsed, nil
		}

		parsed, err = time.Parse(time.DateOnly, trimmed)
		if err == nil {
			return parsed, nil
		}

		return time.Time{}, fmt.Errorf("%w: time from %q", ErrValueCoercion, trimmed)
	default:
		return time.Time{}, fmt.Errorf("%w: time from %T", ErrValueCoercion, value)
	}
}

// matchKeyIn returns a selector predicate matching the given match-key column against any of values
func matchKeyIn(field string, values []string) func(*sql.Selector) {
	return func(s *sql.Selector) {
		s.Where(sql.In(s.C(field), lo.ToAnySlice(values)...))
	}
}

// ingestQueryChunkSize bounds the number of values pushed into a single IN predicate
const ingestQueryChunkSize = 500

const (
	// FieldOwnerID is the provenance column recording the owning organization
	FieldOwnerID = "owner_id"
	// FieldIntegrationID is the provenance column recording the writing installation's FK
	FieldIntegrationID = "integration_id"
	// FieldManagedBy is the provenance column recording which installation owns a record
	FieldManagedBy = "managed_by"
	// FieldPlatformID is the provenance column recording the platform of the writing installation
	FieldPlatformID = "platform_id"
	// FieldSourceDefinitionID is the provenance column recording the source definition id
	FieldSourceDefinitionID = "source_definition_id"
	// FieldSourceDefinitionVersion is the provenance column recording the source definition version
	FieldSourceDefinitionVersion = "source_definition_version"
	// FieldSourceInstanceID is the provenance column recording the external tenant or instance
	FieldSourceInstanceID = "source_instance_id"
	// FieldIntegrationRunID is the provenance column recording the integration run that last wrote a record
	FieldIntegrationRunID = "integration_run_id"
)

// StampProvenance writes the schema's trusted integration-derived provenance columns and ownership
// edges onto an ingest payload from the writing installation, overriding anything the mapping
// emitted for them; it is the sole writer of provenance columns for both the synchronous and the
// durable ingest paths, so a queued record persists with the same provenance a batched one does
func StampProvenance(payload json.RawMessage, schema *Schema, integration *generated.Integration, runID string) json.RawMessage {
	values := []struct {
		field string
		value string
	}{
		{FieldOwnerID, integration.OwnerID},
		{FieldIntegrationID, integration.ID},
		{FieldManagedBy, integration.ID},
		{FieldPlatformID, integration.PlatformID},
		{FieldSourceDefinitionID, integration.DefinitionID},
		{FieldSourceDefinitionVersion, integration.DefinitionVersion},
		{FieldSourceInstanceID, integration.InstallationMetadata.Display.ExternalID},
		{FieldIntegrationRunID, runID},
	}

	return jsonx.EditObject(payload, func(doc map[string]json.RawMessage) bool {
		changed := false

		for _, v := range values {
			if v.value == "" {
				continue
			}

			field, ok := schema.FieldByName(v.field)
			if !ok {
				continue
			}

			if stampProvenanceKey(doc, field.Name, v.value) {
				changed = true
			}
		}

		if schema.IntegrationM2MEdge != "" {
			if edge, ok := schema.EdgeByName(schema.IntegrationM2MEdge); ok && stampProvenanceKey(doc, edge.CreateField, []string{integration.ID}) {
				changed = true
			}
		}

		if runID != "" && schema.IntegrationRunM2MEdge != "" {
			if edge, ok := schema.EdgeByName(schema.IntegrationRunM2MEdge); ok && stampProvenanceKey(doc, edge.CreateField, []string{runID}) {
				changed = true
			}
		}

		return changed
	})
}

// stampProvenanceKey writes value to key unconditionally, reporting whether the stored bytes changed
func stampProvenanceKey(doc map[string]json.RawMessage, key string, value any) bool {
	encoded, err := json.Marshal(value)
	if err != nil {
		return false
	}

	if raw, ok := doc[key]; ok && bytes.Equal(raw, encoded) {
		return false
	}

	doc[key] = encoded

	return true
}

// applyStampedFields sets the stamped provenance keys carried by payload on the mutation by name, for
// fields the schema's GraphQL input type does not carry
func applyStampedFields(mutation ent.Mutation, payload json.RawMessage, fields ...string) error {
	for _, field := range fields {
		v := lookupValue(payload, field)
		if v == "" {
			continue
		}

		if err := mutation.SetField(field, v); err != nil {
			return err
		}
	}

	return nil
}

// carryStampedKeys copies the stamped provenance keys carried by payload onto prepared, which was
// re-encoded through the GraphQL create input type and so no longer holds them
func carryStampedKeys(prepared, payload json.RawMessage, fields ...string) (json.RawMessage, error) {
	for _, field := range fields {
		v := lookupValue(payload, field)
		if v == "" {
			continue
		}

		var err error

		if prepared, _, err = jsonx.SetObjectKey(prepared, field, v); err != nil {
			return nil, err
		}
	}

	return prepared, nil
}

// activeIntegrationsKey carries the ctx-scoped set of integration active answers
var activeIntegrationsKey = contextx.NewKey[map[string]bool]()

// WithActiveIntegrations installs a ctx-carried set of integration ids known to be active
func WithActiveIntegrations(ctx context.Context, ids []string) context.Context {
	set := make(map[string]bool, len(ids))
	for _, id := range ids {
		set[id] = true
	}

	return activeIntegrationsKey.Set(ctx, set)
}

// integrationActive reports whether the given integration is active
func integrationActive(ctx context.Context, client *generated.Client, integrationID string) (bool, error) {
	if set, ok := activeIntegrationsKey.Get(ctx); ok {
		return set[integrationID], nil
	}

	return client.Integration.Query().Where(integration.ID(integrationID)).Exist(ctx)
}

// filterByAlternativeFields keeps rows whose lookup alternative field values match one of the key tuples
func filterByAlternativeFields(rows []json.RawMessage, fields []string, keys []LookupValues) []json.RawMessage {
	kept := make([]json.RawMessage, 0, len(rows))

	for _, row := range rows {
		rowValues := make(LookupValues, len(fields))
		for _, field := range fields {
			rowValues[field] = lookupValue(row, field)
		}

		if lo.SomeBy(keys, func(key LookupValues) bool {
			return lo.EveryBy(fields, func(field string) bool { return rowValues[field] == key[field] })
		}) {
			kept = append(kept, row)
		}
	}

	return kept
}

// lookupKeyFor resolves the first lookup alternative fully present in the payload
func lookupKeyFor(s *Schema, payload json.RawMessage) (alternative int, values LookupValues, ok bool) {
	for i, alt := range s.Lookup {
		candidate := make(LookupValues, len(alt.Fields))

		complete := true

		for _, name := range alt.Fields {
			field, found := s.FieldByName(name)
			if !found {
				complete = false
				break
			}

			value := lookupValue(payload, field.InputKey)
			if value == "" {
				complete = false
				break
			}

			candidate[name] = value
		}

		if complete {
			return i, candidate, true
		}
	}

	return 0, nil, false
}

// EncodeLookupKey renders a lookup alternative's key values into the lookup cache key
func EncodeLookupKey(alternative LookupAlternative, keys LookupValues) string {
	parts := make([]string, len(alternative.Fields))
	for i, field := range alternative.Fields {
		parts[i] = keys[field]
	}

	return strings.Join(parts, "\x1f")
}

// lookupMatchKey identifies one cached ingest lookup match by schema, alternative index, and key tuple
type lookupMatchKey struct {
	schema      string
	alternative int
	keys        string
}

// lookupMatchEntry is one cached ingest lookup match of prefetched rows and same-run created ids
type lookupMatchEntry struct {
	rows       []json.RawMessage
	createdIDs []string
}

// lookupMatchCache is the ctx-carried prefetch cache for ingest lookup matches
type lookupMatchCache map[lookupMatchKey]lookupMatchEntry

// lookupMatchCacheContextKey carries the prefetch cache installed by WithLookupMatches
var lookupMatchCacheContextKey = contextx.NewKey[lookupMatchCache]()

// WithLookupMatches installs a ctx-carried cache of one schema's ingest lookup matches by alternative and key
func WithLookupMatches(ctx context.Context, schema *Schema, matches map[int]map[string][]json.RawMessage) context.Context {
	cache, ok := lookupMatchCacheContextKey.Get(ctx)
	if !ok {
		cache = lookupMatchCache{}
	}

	for alternative, byKey := range matches {
		for keys, rows := range byKey {
			cache[lookupMatchKey{schema: schema.Snake, alternative: alternative, keys: keys}] = lookupMatchEntry{rows: rows}
		}
	}

	return lookupMatchCacheContextKey.Set(ctx, cache)
}

// selectIngestCandidate selects the single row an ingest write applies to from the lookup matches
func selectIngestCandidate(s *Schema, rows []json.RawMessage, payload json.RawMessage) (row json.RawMessage, claimable bool, foreign bool, err error) {
	me := lookupValue(payload, FieldManagedBy)

	managedByMe := lo.Filter(rows, func(candidate json.RawMessage, _ int) bool {
		return lookupValue(candidate, FieldManagedBy) == me
	})

	switch len(managedByMe) {
	case 0:
	case 1:
		return managedByMe[0], false, false, nil
	default:
		return nil, false, false, ErrUpsertConflict
	}

	pd := lookupValue(payload, FieldSourceDefinitionID)
	pi := lookupValue(payload, FieldSourceInstanceID)

	var ownedPartial, unclaimed, foreignRows []json.RawMessage

	for _, candidate := range rows {
		rd := lookupValue(candidate, FieldSourceDefinitionID)
		ri := lookupValue(candidate, FieldSourceInstanceID)

		switch {
		case pd == "":
			ownedPartial = append(ownedPartial, candidate)
		case rd == pd && ri == pi:
			ownedPartial = append(ownedPartial, candidate)
		case rd == "":
			unclaimed = append(unclaimed, candidate)
		default:
			foreignRows = append(foreignRows, candidate)
		}
	}

	switch len(ownedPartial) {
	case 0:
	case 1:
		return ownedPartial[0], false, false, nil
	default:
		return nil, false, false, ErrUpsertConflict
	}

	switch len(unclaimed) {
	case 0:
	case 1:
		return unclaimed[0], true, false, nil
	default:
		return nil, false, false, ErrUpsertConflict
	}

	if s.InstanceScoped {
		foreignRows = lo.Filter(foreignRows, func(candidate json.RawMessage, _ int) bool {
			return lookupValue(candidate, FieldSourceInstanceID) == pi
		})
	}

	switch len(foreignRows) {
	case 0:
		return nil, false, false, nil
	case 1:
		return foreignRows[0], false, true, nil
	default:
		return nil, false, false, ErrUpsertConflict
	}
}

// DisplayField returns the schema's display-name field; generation enforces at most one
func (s *Schema) DisplayField() (FieldDescriptor, bool) {
	for _, f := range s.Fields {
		if f.DisplayKey {
			return f, true
		}
	}

	return FieldDescriptor{}, false
}

// DisplayValue returns the display-name value from a loaded row, or empty when the schema
// declares no display field or the row lacks a value
func (s *Schema) DisplayValue(row json.RawMessage) string {
	field, ok := s.DisplayField()
	if !ok {
		return ""
	}

	return lookupValue(row, field.Name)
}

// Upsert creates or updates the row matching the payload's lookup key through the ingest capability
func (s *Schema) Upsert(ctx context.Context, client *generated.Client, ownerID string, payload json.RawMessage) (id string, changed bool, managed bool, err error) {
	ref := SchemaRef{Schema: s.Snake, Operation: refOpUpsert}

	if s.Create == nil || s.Ingest == nil || s.Ingest.buildUpdate == nil {
		return "", false, false, logError(ctx, ref, ErrUpsertUnsupported, nil)
	}

	alternative, keys, hasKey := lookupKeyFor(s, payload)

	var (
		rows      []json.RawMessage
		cacheKey  lookupMatchKey
		cacheable bool
	)

	switch {
	case !hasKey:
		return "", false, false, ErrUpsertKeyMissing
	default:
		cacheKey = lookupMatchKey{schema: s.Snake, alternative: alternative, keys: EncodeLookupKey(s.Lookup[alternative], keys)}

		cache, ok := lookupMatchCacheContextKey.Get(ctx)
		if !ok {
			rows, err = s.QueryByLookup(ctx, client, ownerID, alternative, []LookupValues{keys})
			if err != nil {
				return "", false, false, err
			}

			break
		}

		cacheable = true

		entry, present := cache[cacheKey]
		if !present {
			rows, err = s.QueryByLookup(ctx, client, ownerID, alternative, []LookupValues{keys})
			if err != nil {
				return "", false, false, err
			}

			break
		}

		for _, createdID := range entry.createdIDs {
			row, lerr := s.Load(ctx, client, createdID)
			if lerr != nil {
				return "", false, false, lerr
			}

			entry.rows = append(entry.rows, row)
		}

		if len(entry.createdIDs) > 0 {
			entry.createdIDs = nil
			cache[cacheKey] = entry
		}

		rows = entry.rows
	}

	candidate, _, foreign, err := selectIngestCandidate(s, rows, payload)
	if err != nil {
		return "", false, false, logError(ctx, ref, err, fmt.Errorf("%s lookup matched conflicting records", s.Name))
	}

	if foreign {
		logx.FromContext(ctx).Debug().Str(FieldSchema, s.Snake).Str(fieldEntityID, entityID(candidate)).Msg("ingest skipped record managed by another definition")

		return entityID(candidate), false, false, nil
	}

	if candidate == nil {
		id, err = s.Create(ctx, client, payload)
		if err != nil {
			return "", false, false, err
		}

		if cacheable {
			if cache, ok := lookupMatchCacheContextKey.Get(ctx); ok {
				entry := cache[cacheKey]
				entry.createdIDs = append(entry.createdIDs, id)
				cache[cacheKey] = entry
			}
		}

		return id, true, true, nil
	}

	id = entityID(candidate)

	_, hasOwner := s.FieldByName(FieldOwnerID)
	if id == "" || (hasOwner && lookupValue(candidate, FieldOwnerID) != ownerID) {
		return "", false, false, logError(ctx, ref, ErrUpsertConflict, fmt.Errorf("invalid or cross-organization match for %s", s.Name))
	}

	changed, managed, err = s.applyIngestUpdate(ctx, client, candidate, payload)

	return id, changed, managed, err
}

// pruneIngestFields drops unchanged and volatile-only assignments from the mutation
func (s *Schema) pruneIngestFields(ctx context.Context, mutation ent.Mutation) (ChangeSet, error) {
	var volatile []string

	material := false

	for _, name := range NormalizeStrings(append(mutation.Fields(), mutation.ClearedFields()...)) {
		field, ok := s.FieldByName(name)
		if !ok {
			return ChangeSet{}, fmt.Errorf("%w: %s.%s", ErrFieldNotFound, s.Name, name)
		}

		old, err := mutation.OldField(ctx, name)
		if err != nil {
			return ChangeSet{}, err
		}

		proposed, _ := mutation.Field(name)
		if field.Equal(old, proposed) {
			if err := mutation.ResetField(name); err != nil {
				return ChangeSet{}, err
			}

			continue
		}

		if field.Volatile {
			volatile = append(volatile, name)

			continue
		}

		material = true
	}

	set := ChangeSetFromMutation(mutation)

	edgeChanged := lo.SomeBy(set.ChangedEdges, func(name string) bool {
		if name == s.IntegrationM2MEdge || name == s.IntegrationRunM2MEdge {
			return false
		}

		edge, ok := s.EdgeByName(name)

		return !ok || edge.Field == "" || !lo.Contains(volatile, edge.Field)
	})

	if material || edgeChanged {
		return set, nil
	}

	for _, name := range volatile {
		if err := mutation.ResetField(name); err != nil {
			return ChangeSet{}, err
		}
	}

	for _, name := range []string{s.IntegrationM2MEdge, s.IntegrationRunM2MEdge} {
		if name == "" || !lo.Contains(set.ChangedEdges, name) {
			continue
		}

		if err := mutation.ResetEdge(name); err != nil {
			return ChangeSet{}, err
		}
	}

	return ChangeSetFromMutation(mutation), nil
}

// SystemControlledOnly reports whether the change set touches only system-controlled columns and edges
func (s *Schema) SystemControlledOnly(set ChangeSet) bool {
	if len(set.ChangedFields) == 0 && len(set.ChangedEdges) == 0 {
		return false
	}

	bookkeepingEdges := lo.EveryBy(set.ChangedEdges, func(name string) bool {
		if name == s.IntegrationM2MEdge || name == s.IntegrationRunM2MEdge {
			return true
		}

		edge, ok := s.EdgeByName(name)

		return ok && s.IntegrationFKField != "" && edge.Field == s.IntegrationFKField
	})

	if !bookkeepingEdges {
		return false
	}

	return lo.EveryBy(set.ChangedFields, func(name string) bool {
		field, ok := s.FieldByName(name)

		return ok && field.SystemControlled
	})
}

// applyIngestClaim reports whether the writing installation may own the resolved row
func (s *Schema) applyIngestClaim(ctx context.Context, client *generated.Client, row json.RawMessage, payload json.RawMessage) (bool, error) {
	manager := lookupValue(row, FieldManagedBy)
	me := lookupValue(payload, FieldManagedBy)

	if manager == "" || manager == me {
		return true, nil
	}

	active, err := integrationActive(ctx, client, manager)
	if err != nil {
		return false, err
	}

	return !active, nil
}

// applyIngestResurrect clears a non-episodic removal field in the payload when the resolved row carries one
func (s *Schema) applyIngestResurrect(row json.RawMessage, payload json.RawMessage) json.RawMessage {
	if s.RemovedAtField == "" || s.RemovedAtEpisodic {
		return payload
	}

	if lookupValue(row, s.RemovedAtField) == "" {
		return payload
	}

	field, _ := s.FieldByName(s.RemovedAtField)

	edited, _, err := jsonx.SetObjectKey(payload, field.InputKey, nil)
	if err != nil {
		return payload
	}

	return edited
}

// applyIngestUpdate applies the shared ingest write decision to one resolved row
func (s *Schema) applyIngestUpdate(ctx context.Context, client *generated.Client, row json.RawMessage, payload json.RawMessage) (changed bool, managed bool, err error) {
	owned, err := s.applyIngestClaim(ctx, client, row, payload)
	if err != nil {
		return false, true, err
	}

	if !owned {
		return false, false, nil
	}

	payload = s.applyIngestResurrect(row, payload)

	rekeyed, throughIDs := splitThroughEdgeIDs(s, s.rekeyEdgesForUpdate(payload))

	mutation, save, err := s.Ingest.buildUpdate(ctx, client, row, rekeyed)
	if err != nil {
		return false, true, err
	}

	changes, err := s.pruneIngestFields(ctx, mutation)
	if err != nil {
		return false, true, err
	}

	bookkeeping := s.SystemControlledOnly(changes)

	if !changes.Empty() {
		saveCtx := ctx
		if bookkeeping {
			saveCtx = WithEmissionVetoed(ctx)
		}

		if err := save(saveCtx); err != nil {
			return false, true, err
		}
	}

	if len(throughIDs) > 0 {
		if err := applyThroughEdgeIDs(ctx, client, s, entityID(row), throughIDs); err != nil {
			return false, true, err
		}
	}

	return (!changes.Empty() && !bookkeeping) || len(throughIDs) > 0, true, nil
}

// rekeyEdgesForUpdate renames to-many edge keys in a create-input payload to their update-input add
// keys, so cross-object links injected at map time also apply on the re-ingest update path. Links
// are additive on update: edges carry no provenance, so targets no longer matched are never removed.
// Unique edge keys are shared between create and update inputs and pass through unchanged; keys for
// immutable edges have no update setter and are dropped by decode
func (s *Schema) rekeyEdgesForUpdate(payload json.RawMessage) json.RawMessage {
	return jsonx.EditObject(payload, func(doc map[string]json.RawMessage) bool {
		changed := false

		for _, edge := range s.Edges {
			if edge.AddField == "" {
				continue
			}

			raw, ok := doc[edge.CreateField]
			if !ok {
				continue
			}

			doc[edge.AddField] = raw
			delete(doc, edge.CreateField)
			changed = true
		}

		return changed
	})
}

// FieldValue returns the trimmed string value of one field from a marshaled entity row
func FieldValue(row json.RawMessage, field string) string {
	return lookupValue(row, field)
}

// lookupValue extracts the string value of one create-input key from the payload
func lookupValue(payload json.RawMessage, key string) string {
	value, _ := jsonx.DecodeObjectKey[string](payload, key)

	return strings.TrimSpace(value)
}

// entityID extracts the id column from one marshaled entity row
func entityID(row json.RawMessage) string {
	id, _ := jsonx.DecodeObjectKey[string](row, "id")

	return id
}

// --- Per-schema registrations ---

var (
	SchemaOrgMembership = &Schema{
		SchemaDescriptor: SchemaDescriptor{
			Name:  "OrgMembership",
			Snake: "org_membership",
			Lower: "orgmembership",
		},
		Load: func(ctx context.Context, client *generated.Client, entityID string) (json.RawMessage, error) {
			ref := SchemaRef{Schema: "org_membership", Operation: refOpLoad, EntityID: entityID}

			entity, err := client.OrgMembership.Get(ctx, entityID)
			if err != nil {
				return nil, logError(ctx, ref, ErrLoadFailed, err)
			}

			data, err := json.Marshal(entity)
			if err != nil {
				return nil, logError(ctx, ref, ErrMarshalFailed, err)
			}

			return data, nil
		},
	}
	SchemaOrganization = &Schema{
		SchemaDescriptor: SchemaDescriptor{
			Name:  "Organization",
			Snake: "organization",
			Lower: "organization",
		},
		Load: func(ctx context.Context, client *generated.Client, entityID string) (json.RawMessage, error) {
			ref := SchemaRef{Schema: "organization", Operation: refOpLoad, EntityID: entityID}

			entity, err := client.Organization.Get(ctx, entityID)
			if err != nil {
				return nil, logError(ctx, ref, ErrLoadFailed, err)
			}

			data, err := json.Marshal(entity)
			if err != nil {
				return nil, logError(ctx, ref, ErrMarshalFailed, err)
			}

			return data, nil
		},
	}
	SchemaWorkflowInstance = &Schema{
		SchemaDescriptor: SchemaDescriptor{
			Name:             "WorkflowInstance",
			Snake:            "workflow_instance",
			Lower:            "workflowinstance",
			WorkflowEligible: true,
		},
		ProjectionType: reflect.TypeFor[WorkflowInstanceProjection](),
		Load: func(ctx context.Context, client *generated.Client, entityID string) (json.RawMessage, error) {
			ref := SchemaRef{Schema: "workflow_instance", Operation: refOpLoad, EntityID: entityID}

			entity, err := client.WorkflowInstance.Get(ctx, entityID)
			if err != nil {
				return nil, logError(ctx, ref, ErrLoadFailed, err)
			}

			data, err := json.Marshal(entity)
			if err != nil {
				return nil, logError(ctx, ref, ErrMarshalFailed, err)
			}

			return data, nil
		},
		LoadObject: func(ctx context.Context, client *generated.Client, entityID string) (any, error) {
			entity, err := client.WorkflowInstance.Get(ctx, entityID)
			if err != nil {
				return nil, logError(ctx, SchemaRef{Schema: "workflow_instance", Operation: refOpLoad, EntityID: entityID}, ErrLoadFailed, err)
			}

			return entity, nil
		},
	}
	SchemaWorkflowObjectRef = &Schema{
		SchemaDescriptor: SchemaDescriptor{
			Name:             "WorkflowObjectRef",
			Snake:            "workflow_object_ref",
			Lower:            "workflowobjectref",
			WorkflowEligible: true,
		},
		ProjectionType: reflect.TypeFor[WorkflowObjectRefProjection](),
		Load: func(ctx context.Context, client *generated.Client, entityID string) (json.RawMessage, error) {
			ref := SchemaRef{Schema: "workflow_object_ref", Operation: refOpLoad, EntityID: entityID}

			entity, err := client.WorkflowObjectRef.Get(ctx, entityID)
			if err != nil {
				return nil, logError(ctx, ref, ErrLoadFailed, err)
			}

			data, err := json.Marshal(entity)
			if err != nil {
				return nil, logError(ctx, ref, ErrMarshalFailed, err)
			}

			return data, nil
		},
		LoadObject: func(ctx context.Context, client *generated.Client, entityID string) (any, error) {
			entity, err := client.WorkflowObjectRef.Get(ctx, entityID)
			if err != nil {
				return nil, logError(ctx, SchemaRef{Schema: "workflow_object_ref", Operation: refOpLoad, EntityID: entityID}, ErrLoadFailed, err)
			}

			return entity, nil
		},
	}
)

// init wires cross-schema edge references after all Schema vars are initialized
func init() {
	SchemaOrgMembership.Fields = []FieldDescriptor{
		{Name: "organization_id", Label: "OrganizationID", Type: "string", MatchKey: true, SystemControlled: true},
		{Name: "role", Label: "Role", Type: "enums.Role"},
		{Name: "user_id", Label: "UserID", Type: "string", MatchKey: true},
	}
	SchemaOrganization.Fields = []FieldDescriptor{
		{Name: "created_at", Label: "CreatedAt", Type: "time.Time", Clearable: true, SystemControlled: true},
		{Name: "created_by", Label: "CreatedBy", Type: "string", MatchKey: true, Clearable: true, SystemControlled: true},
		{Name: "description", Label: "Description", Type: "string", MatchKey: true, Clearable: true},
		{Name: "display_id", Label: "DisplayID", Type: "string", MatchKey: true},
		{Name: "name", Label: "Name", Type: "string", MatchKey: true},
		{Name: "preferences", Label: "Preferences", Type: "map[string]interface {}", Clearable: true, TaskRules: []TaskRuleDescriptor{{RuleID: "import-existing-policies", Expression: "value.policies.has_existing == true", Trigger: "createOnly"}, {RuleID: "framework", EachElement: "value.frameworks"}}},
		{Name: "updated_at", Label: "UpdatedAt", Type: "time.Time", Clearable: true, SystemControlled: true},
		{Name: "updated_by", Label: "UpdatedBy", Type: "string", MatchKey: true, Clearable: true, SystemControlled: true},
	}
	SchemaWorkflowInstance.Fields = []FieldDescriptor{
		{Name: "status", Label: "Status", Type: "string", WorkflowEligible: true, MatchKey: true, Clearable: true},
	}
	SchemaWorkflowObjectRef.Fields = []FieldDescriptor{
		{Name: "organization_id", Label: "OrganizationID", Type: "string", MatchKey: true, Clearable: true, SystemControlled: true},
		{Name: "workflow_instance_id", Label: "WorkflowInstanceID", Type: "string", MatchKey: true},
	}
	SchemaOrganization.TaskRules = []TaskRuleDescriptor{
		{RuleID: "setup-payment-method"},
	}
	SchemaOrgMembership.Edges = []EdgeDescriptor{
		{
			Name:        "organization",
			Label:       "Organization",
			Target:      SchemaOrganization,
			TargetType:  "Organization",
			Unique:      true,
			CreateField: "organization_id",
			Field:       "organization_id",
		},
	}
	SchemaWorkflowObjectRef.Edges = []EdgeDescriptor{
		{
			Name:             "organization",
			Label:            "Organization",
			Target:           SchemaOrganization,
			TargetType:       "Organization",
			Unique:           true,
			CreateField:      "organization_id",
			Field:            "organization_id",
			WorkflowEligible: true,
		},
		{
			Name:        "workflow_instance",
			Label:       "WorkflowInstance",
			Target:      SchemaWorkflowInstance,
			TargetType:  "WorkflowInstance",
			Unique:      true,
			CreateField: "workflow_instance_id",
			Field:       "workflow_instance_id",
		},
	}

	// through edges are linked by creating join entity rows — one per target, each with its own
	// generated id — so wrap the create and update closures of schemas that have them: through-edge
	// id lists are split out of the payload and applied as rows after the mutation succeeds
	for _, s := range allSchemas {
		if !slices.ContainsFunc(s.Edges, func(e EdgeDescriptor) bool { return e.Through }) {
			continue
		}

		schema := s

		if create := schema.Create; create != nil {
			schema.Create = func(ctx context.Context, client *generated.Client, input json.RawMessage) (string, error) {
				input, throughIDs := splitThroughEdgeIDs(schema, input)

				id, err := create(ctx, client, input)
				if err != nil {
					return id, err
				}

				return id, applyThroughEdgeIDs(ctx, client, schema, id, throughIDs)
			}
		}

		if update := schema.Update; update != nil {
			schema.Update = func(ctx context.Context, client *generated.Client, entityID string, input json.RawMessage) error {
				input, throughIDs := splitThroughEdgeIDs(schema, input)

				if err := update(ctx, client, entityID, input); err != nil {
					return err
				}

				return applyThroughEdgeIDs(ctx, client, schema, entityID, throughIDs)
			}
		}
	}
}

// splitThroughEdgeIDs removes through-edge id lists from a create or update payload, returning the
// cleaned payload and the target ids per edge name. Malformed values are left in place so input
// validation rejects them instead of being silently discarded
func splitThroughEdgeIDs(s *Schema, payload json.RawMessage) (json.RawMessage, map[string][]string) {
	if s == nil {
		return payload, nil
	}

	var ids map[string][]string

	cleaned := jsonx.EditObject(payload, func(doc map[string]json.RawMessage) bool {
		for _, edge := range s.Edges {
			if !edge.Through {
				continue
			}

			raw, ok := doc[edge.CreateField]
			if !ok {
				continue
			}

			targetIDs, err := jsonx.Decode[[]string](raw)
			if err != nil {
				continue
			}

			if ids == nil {
				ids = map[string][]string{}
			}

			ids[edge.Name] = targetIDs
			delete(doc, edge.CreateField)
		}

		return ids != nil
	})

	if ids == nil {
		return payload, nil
	}

	return cleaned, ids
}

// applyThroughEdgeIDs creates the join entity rows for each split through edge
func applyThroughEdgeIDs(ctx context.Context, client *generated.Client, s *Schema, sourceID string, ids map[string][]string) error {
	if s == nil || len(ids) == 0 {
		return nil
	}

	for name, targetIDs := range ids {
		edge, ok := s.EdgeByName(name)
		if !ok || edge.LinkThrough == nil || len(targetIDs) == 0 {
			continue
		}

		if err := edge.LinkThrough(ctx, client, sourceID, targetIDs); err != nil {
			return logError(ctx, SchemaRef{Schema: s.Snake, Operation: refOpLink, EntityID: sourceID, Edge: name}, ErrLinkFailed, err)
		}
	}

	return nil
}

// --- Lookup registry ---

var allSchemas = []*Schema{
	SchemaOrgMembership,
	SchemaOrganization,
	SchemaWorkflowInstance,
	SchemaWorkflowObjectRef,
}

var (
	schemaLookupOnce sync.Once
	schemaLookupMap  map[string]*Schema
)

func buildSchemaLookup() {
	schemaLookupOnce.Do(func() {
		schemaLookupMap = make(map[string]*Schema, len(allSchemas)*3)

		for _, s := range allSchemas {
			schemaLookupMap[s.Name] = s
			schemaLookupMap[s.Snake] = s
			schemaLookupMap[s.Lower] = s
		}
	})
}

// LookupSchema resolves a schema by any known name variation (PascalCase, snake_case,
// camelCase, or lowercase). Returns the schema and whether a match was found.
func LookupSchema(name string) (*Schema, bool) {
	buildSchemaLookup()

	if s, ok := schemaLookupMap[name]; ok {
		return s, true
	}

	if s, ok := schemaLookupMap[normalizeSchemaKey(name)]; ok {
		return s, true
	}

	return nil, false
}

// normalizeSchemaKey lowers a schema name and strips separators for fuzzy catalog lookup.
func normalizeSchemaKey(name string) string {
	return strings.ToLower(strings.NewReplacer("_", "", "-", "", " ", "").Replace(name))
}

// AllSchemas returns a copy of all registered schemas
func AllSchemas() []*Schema {
	result := make([]*Schema, len(allSchemas))
	copy(result, allSchemas)

	return result
}

// selectTargets queries entities matching a target selector and filters them with a typed CEL
// evaluator bound to the target schema's native projection — and, when the selector carries
// SourceContext with a SourceSchema, the source schema's projection as "source" — so selector
// expressions resolve typed fields rather than evaluating against a map[string]any
func selectTargets(ctx context.Context, client *generated.Client, orgID string, selector TargetSelector) ([]entityRef, error) {
	schema, ok := LookupSchema(selector.Schema.Name)
	if !ok {
		return nil, logError(ctx, SchemaRef{Schema: selector.Schema.Snake, Operation: refOpQuery}, ErrSchemaNotFound, fmt.Errorf("schema %s is not registered", selector.Schema.Name))
	}

	entities, err := selectCandidates(ctx, client, schema, orgID, selector)
	if err != nil {
		return nil, err
	}

	if selector.Unique && schema.InstanceScoped {
		pi := lookupValue(selector.SourceContext, FieldSourceInstanceID)

		entities = lo.Filter(entities, func(row json.RawMessage, _ int) bool {
			return lookupValue(row, FieldSourceInstanceID) == pi
		})
	}

	var (
		eval      *celx.NativeEntityEvaluator
		useSource bool
	)

	if selector.Expression != "" {
		if schema.ProjectionType == nil {
			return nil, fmt.Errorf("%w: %s has no projection for expression evaluation", ErrEvaluatorBuildFailed, schema.Name)
		}

		var sourceType reflect.Type

		if len(selector.SourceContext) > 0 && !selector.SourceSchema.IsZero() {
			if src, ok := LookupSchema(selector.SourceSchema.Name); ok && src.ProjectionType != nil {
				sourceType = src.ProjectionType
				useSource = true
			}
		}

		envCfg := celx.StrictEnvConfig()
		envCfg.CrossTypeNumericComparisons = true

		eval, err = celx.NewNativeEntityEvaluator(envCfg, celx.FastEvalConfig(), schema.ProjectionType, sourceType)
		if err != nil {
			errorEvent(ctx, SchemaRef{Schema: schema.Snake, Operation: refOpQuery}, err).Str(fieldExpression, selector.Expression).Msg(ErrEvaluatorBuildFailed.Error())

			return nil, fmt.Errorf("%w: %w", ErrEvaluatorBuildFailed, err)
		}

		logx.FromContext(ctx).Debug().Str(FieldSchema, schema.Snake).Str(fieldExpression, selector.Expression).Int("candidates", len(entities)).Msg("entityops: filtering targets with expression")
	}

	excludeSet := mapx.MapSetFromSlice(selector.ExcludeIDs)

	var results []entityRef

	for _, data := range entities {
		id := entityID(data)
		if id == "" {
			continue
		}

		if _, excluded := excludeSet[id]; excluded {
			continue
		}

		if selector.Expression != "" {
			var (
				match   bool
				evalErr error
			)

			if useSource {
				match, evalErr = eval.EvaluateBoolWithSource(ctx, selector.Expression, data, selector.SourceContext)
			} else {
				match, evalErr = eval.EvaluateBool(ctx, selector.Expression, data)
			}

			if evalErr != nil {
				errorEvent(ctx, SchemaRef{Schema: schema.Snake, Operation: refOpQuery, EntityID: id}, evalErr).Str(fieldExpression, selector.Expression).Msg(ErrEvaluationFailed.Error())
				continue
			}

			if !match {
				continue
			}
		}

		results = append(results, entityRef{ID: id, Schema: schema.SchemaDescriptor})
	}

	return results, nil
}

// selectCandidates resolves the candidate entity set for a target selector
func selectCandidates(ctx context.Context, client *generated.Client, schema *Schema, orgID string, selector TargetSelector) ([]json.RawMessage, error) {
	if selector.KeyMatch != nil {
		if schema.QueryByKey == nil {
			return nil, fmt.Errorf("%w: %s", ErrKeyMatchUnsupported, schema.Name)
		}

		values := collectKeyValues(selector.SourceContext, selector.KeyMatch)
		if len(values) == 0 {
			return nil, nil
		}

		if cache, ok := linkTargetCacheContextKey.Get(ctx); ok {
			return lookupLinkTargetCache(cache, schema.Snake, selector.KeyMatch.TargetField, values), nil
		}

		return schema.QueryByKey(ctx, client, orgID, selector.KeyMatch.TargetField, values)
	}

	if schema.Query == nil {
		return nil, fmt.Errorf("%w: %s", ErrQueryUnsupported, schema.Name)
	}

	return schema.Query(ctx, client, orgID)
}

// linkTargetCacheKey identifies one cached target lookup by target schema, field, and value
type linkTargetCacheKey struct {
	schema string
	field  string
	value  string
}

// linkTargetCache is the ctx-carried prefetch cache for link target rows
type linkTargetCache map[linkTargetCacheKey][]json.RawMessage

// linkTargetCacheContextKey carries the prefetch cache installed by PrefetchLinkTargets
var linkTargetCacheContextKey = contextx.NewKey[linkTargetCache]()

// lookupLinkTargetCache collects the cached rows for every value, deduplicated by entity id
func lookupLinkTargetCache(cache linkTargetCache, schemaSnake, field string, values []string) []json.RawMessage {
	seen := map[string]struct{}{}

	var rows []json.RawMessage

	for _, value := range values {
		for _, row := range cache[linkTargetCacheKey{schema: schemaSnake, field: field, value: value}] {
			id := entityID(row)
			if _, ok := seen[id]; ok {
				continue
			}

			seen[id] = struct{}{}
			rows = append(rows, row)
		}
	}

	return rows
}

// collectKeyValues extracts the deduplicated, non-empty source-side key values for a KeyMatch
// from the source entity JSON, combining the scalar SourceField with the SourceList values
func collectKeyValues(sourceContext json.RawMessage, km *KeyMatch) []string {
	if len(sourceContext) == 0 {
		return nil
	}

	var values []string

	if km.SourceField != "" {
		if value, ok := jsonx.DecodeObjectKey[string](sourceContext, km.SourceField); ok {
			values = append(values, value)
		}
	}

	if km.SourceList != "" {
		if list, ok := jsonx.DecodeObjectKey[[]string](sourceContext, km.SourceList); ok {
			values = append(values, list...)
		}
	}

	return lo.Uniq(lo.Without(values, ""))
}
