// Code generated by entx/entityops. DO NOT EDIT.

package entityops

import "github.com/theopenlane/entx/vanilla/_example/pkg/gala"

// IngestTopics is the namespace for every generated asynchronous schema-ingest topic.
var IngestTopics = gala.IntegrationIngest.At("entityops")
