package workflowgen

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"text/template"

	"entgo.io/ent/entc"
	"entgo.io/ent/entc/gen"
	"golang.org/x/tools/imports"
)

// ExtensionOption is a function that modifies the Extension configuration
type ExtensionOption func(*Extension)

// Config is the configuration for workflow code generation
type Config struct {
	// EnumsOutputDir is the output directory for workflow object type enums
	EnumsOutputDir string
	// EnumsPackageName is the package name for workflow object type enums
	EnumsPackageName string
}

// Extension implements entc.Extension for workflow-related generated helpers
type Extension struct {
	entc.DefaultExtension
	config *Config
}

// New creates a new workflowgen extension
func New(opts ...ExtensionOption) *Extension {
	ext := &Extension{
		config: &Config{
			EnumsOutputDir:   "./common/enums",
			EnumsPackageName: "enums",
		},
	}

	for _, opt := range opts {
		opt(ext)
	}

	return ext
}

// WithEnumsOutputDir sets the output directory for workflow object type enums
func WithEnumsOutputDir(dir string) ExtensionOption {
	return func(e *Extension) {
		e.config.EnumsOutputDir = dir
	}
}

// WithEnumsPackageName sets the package name for workflow object type enums
func WithEnumsPackageName(name string) ExtensionOption {
	return func(e *Extension) {
		e.config.EnumsPackageName = name
	}
}

// Hooks satisfies the entc.Extension interface
func (e Extension) Hooks() []gen.Hook {
	return []gen.Hook{e.Hook()}
}

// Hook generates the workflow object type enums after ent codegen runs.
// Workflow object/edge capabilities are produced by the entityops generator;
// this extension only emits the WorkflowObjectType enum.
func (e Extension) Hook() gen.Hook {
	return func(next gen.Generator) gen.Generator {
		return gen.GenerateFunc(func(g *gen.Graph) error {
			if err := next.Generate(g); err != nil {
				return err
			}

			ctx := templateContext{
				Graph:            g,
				EnumsPackageName: e.config.EnumsPackageName,
			}

			return e.generateEnums(ctx)
		})
	}
}

// Annotations satisfies the entc.Extension interface.
func (Extension) Annotations() []entc.Annotation { return nil }

// Options satisfies the entc.Extension interface.
func (Extension) Options() []entc.Option { return nil }

// Templates satisfies the entc.Extension interface.
func (Extension) Templates() []*gen.Template { return nil }

// templateContext holds data for rendering templates
type templateContext struct {
	// Graph is the ent code generation graph containing all schema information
	*gen.Graph
	// EnumsPackageName is the package name for generated enum types
	EnumsPackageName string
}

// templateFile represents a template to be rendered and written to a file
type templateFile struct {
	// name is the template name used for parsing and execution
	name string
	// filename is the output filename for the generated file
	filename string
	// outputDir is the directory where the generated file will be written
	outputDir string
	// content is the raw template string content
	content string
}

// generateEnums generates the workflow object type enums
func (e Extension) generateEnums(ctx templateContext) error {
	files := []templateFile{
		{
			name:      "workflow_object_type_enum",
			filename:  "workflow_object_type.go",
			outputDir: e.config.EnumsOutputDir,
			content:   workflowObjectTypeEnumTemplate,
		},
	}

	return renderTemplates(files, ctx)
}

// renderTemplates renders and writes multiple templates based on the provided context
func renderTemplates(files []templateFile, ctx templateContext) error {
	for _, file := range files {
		t, err := template.New(file.name).Funcs(gen.Funcs).Parse(file.content)
		if err != nil {
			return fmt.Errorf("parse %s template: %w", file.name, err)
		}

		if err := writeTemplate(file.outputDir, file.filename, file.name, t, ctx); err != nil {
			return err
		}
	}

	return nil
}

// writeTemplate renders and writes a template to the specified output directory and filename
func writeTemplate(outputDir, filename, templateName string, tmpl *template.Template, data any) error {
	if err := os.MkdirAll(outputDir, 0o755); err != nil { // nolint:mnd
		return fmt.Errorf("create output dir %s: %w", outputDir, err)
	}

	var buf bytes.Buffer
	if err := tmpl.ExecuteTemplate(&buf, templateName, data); err != nil {
		return fmt.Errorf("execute %s template: %w", templateName, err)
	}

	outputPath := filepath.Join(outputDir, filename)

	formatted, err := imports.Process(outputPath, buf.Bytes(), nil)
	if err != nil {
		return fmt.Errorf("format %s: %w", outputPath, err)
	}

	if err := os.WriteFile(outputPath, formatted, 0o600); err != nil { // nolint:mnd
		return fmt.Errorf("write %s: %w", outputPath, err)
	}

	return nil
}

const workflowObjectTypeEnumTemplate = `{{/* Generate WorkflowObjectType enum values based on entities with WorkflowApprovalMixin */}}
{{/* gotype: entgo.io/ent/entc/gen.Graph */}}

{{ define "workflow_object_type_enum" }}
// Code generated by ent. DO NOT EDIT.
// This file is auto-generated to ensure WorkflowObjectType enum matches entities with workflow support.
package {{ .EnumsPackageName }}

import (
	"fmt"
	"io"
)

// WorkflowObjectType enumerates supported object types for workflows.
// These types are automatically generated based on entities that have the WorkflowApprovalMixin.
type WorkflowObjectType string

var (
{{- range $n := $.Nodes }}
	{{- $hasWorkflowFields := false }}
	{{- $isHistory := false }}
	{{- if hasSuffix $n.Name "History" }}{{ $isHistory = true }}{{ end }}
	{{- range $f := $n.Fields }}
		{{- if $f.Annotations.OPENLANE_WORKFLOW_ELIGIBLE }}{{ $hasWorkflowFields = true }}{{ end }}
	{{- end }}
	{{- if and $hasWorkflowFields (not $isHistory) }}
	WorkflowObjectType{{ $n.Name }} WorkflowObjectType = "{{ $n.Name }}"
	{{- end }}
{{- end }}
)

var WorkflowObjectTypes = []string{
{{- range $n := $.Nodes }}
	{{- $hasWorkflowFields := false }}
	{{- $isHistory := false }}
	{{- if hasSuffix $n.Name "History" }}{{ $isHistory = true }}{{ end }}
	{{- range $f := $n.Fields }}
		{{- if $f.Annotations.OPENLANE_WORKFLOW_ELIGIBLE }}{{ $hasWorkflowFields = true }}{{ end }}
	{{- end }}
	{{- if and $hasWorkflowFields (not $isHistory) }}
	string(WorkflowObjectType{{ $n.Name }}),
	{{- end }}
{{- end }}
}

// Values returns all workflow object type values.
func (WorkflowObjectType) Values() (vals []string) {
	return WorkflowObjectTypes
}

// String returns the string representation of the workflow object type.
func (r WorkflowObjectType) String() string { return string(r) }

// ToWorkflowObjectType converts a string to a WorkflowObjectType pointer.
func ToWorkflowObjectType(v string) *WorkflowObjectType {
	switch v {
	{{- range $n := $.Nodes }}
		{{- $hasWorkflowFields := false }}
		{{- $isHistory := false }}
		{{- if hasSuffix $n.Name "History" }}{{ $isHistory = true }}{{ end }}
		{{- range $f := $n.Fields }}
			{{- if $f.Annotations.OPENLANE_WORKFLOW_ELIGIBLE }}{{ $hasWorkflowFields = true }}{{ end }}
		{{- end }}
		{{- if and $hasWorkflowFields (not $isHistory) }}
	case WorkflowObjectType{{ $n.Name }}.String():
		return &WorkflowObjectType{{ $n.Name }}
		{{- end }}
	{{- end }}
	default:
		return nil
	}
}

// MarshalGQL marshals the workflow object type to GraphQL.
func (r WorkflowObjectType) MarshalGQL(w io.Writer) {
	_, _ = w.Write([]byte("\"" + r.String() + "\""))
}

// UnmarshalGQL unmarshals the workflow object type from GraphQL.
func (r *WorkflowObjectType) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("%w, got: %T", ErrWrongTypeWorkflowObjectType, v)
	}
	*r = WorkflowObjectType(str)
	return nil
}

{{ end }}
`
