// Generated by entx integration mapping generator as a starting point. Modify as needed.
package {{ .IngestPackageName }}

import (
	"context"
{{ if .Schema.StockPersist }}
	ent "{{ .EntPackage }}"
	{{ .Schema.EntSchemaPackageAlias }} "{{ .Schema.EntSchemaPackagePath }}"
{{ else }}
	ent "{{ .EntPackage }}"
{{ end -}}
)

// persist{{ .Schema.Name }}Input upserts one {{ .Schema.Name }} record using the ingest lookup key fields
func persist{{ .Schema.Name }}Input(ctx context.Context, db *ent.Client, integration *ent.Integration, createInput ent.{{ .Schema.InputTypeName }}) error {
{{ if .Schema.StockPersist -}}
{{- range .Schema.LookupFields }}
{{ if .Required -}}
	if createInput.{{ .GoField }} == "" {
		return ErrIngestUpsertKeyMissing
	}
{{- else -}}
	if createInput.{{ .GoField }} == nil || *createInput.{{ .GoField }} == "" {
		return ErrIngestUpsertKeyMissing
	}
{{- end }}
{{ end }}
	return persistRoundTripUpsert(
		ctx,
		createInput,
		func(ctx context.Context) (*ent.{{ .Schema.Name }}, error) {
			return db.{{ .Schema.Name }}.Query().
{{- if .Schema.ScopeByIntegrationID }}
				Where({{ .Schema.EntSchemaPackageAlias }}.IntegrationID(integration.ID)).
{{- else }}
				Where({{ .Schema.EntSchemaPackageAlias }}.OwnerID(integration.OwnerID)).
{{- end }}
{{- range .Schema.LookupFields }}
{{ if .Required -}}
				Where({{ $.Schema.EntSchemaPackageAlias }}.{{ .GoField }}(createInput.{{ .GoField }})).
{{- else -}}
				Where({{ $.Schema.EntSchemaPackageAlias }}.{{ .GoField }}(*createInput.{{ .GoField }})).
{{- end }}
{{ end -}}
				Only(ctx)
		},
		func(ctx context.Context, input ent.{{ .Schema.InputTypeName }}) error {
			return db.{{ .Schema.Name }}.Create().SetInput(input).Exec(ctx)
		},
		func(ctx context.Context, existing *ent.{{ .Schema.Name }}, input ent.{{ .Schema.UpdateInputTypeName }}) error {
			return db.{{ .Schema.Name }}.UpdateOneID(existing.ID).SetInput(input).Exec(ctx)
		},
	)
{{ else -}}
	// Custom persistence logic required for {{ .Schema.Name }}.
	// Implement lookup and upsert logic below using the createInput fields.
	panic("not implemented: persist{{ .Schema.Name }}Input")
{{ end -}}
}
