// Generated by entx integration mapping generator as a starting point. Modify as needed.
package {{ .PackageName }}

import (
	"context"
{{ if .Schema.StockPersist }}
	ent "{{ .EntPackage }}"
	{{ .Schema.EntSchemaPackageAlias }} "{{ .Schema.EntSchemaPackagePath }}"
	"{{ .JsonxPackage }}"
{{ else }}
	ent "{{ .EntPackage }}"
{{ end -}}
)

// persist{{ .Schema.Name }}Input upserts one {{ .Schema.Name }} record using the ingest lookup key fields
func persist{{ .Schema.Name }}Input(ctx context.Context, db *ent.Client, integration *ent.Integration, createInput ent.{{ .Schema.InputTypeName }}) error {
{{ if .Schema.StockPersist -}}
	hasKey := false
{{ if .Schema.ScopeByIntegrationID }}
	q := db.{{ .Schema.Name }}.Query().Where({{ .Schema.EntSchemaPackageAlias }}.IntegrationID(integration.ID))
{{ else }}
	q := db.{{ .Schema.Name }}.Query().Where({{ .Schema.EntSchemaPackageAlias }}.OwnerID(integration.OwnerID))
{{ end -}}
{{- range .Schema.LookupFields -}}
{{ if .Required }}
	if createInput.{{ .GoField }} != "" {
		q = q.Where({{ $.Schema.EntSchemaPackageAlias }}.{{ .GoField }}(createInput.{{ .GoField }}))
		hasKey = true
	}
{{ else }}
	if createInput.{{ .GoField }} != nil && *createInput.{{ .GoField }} != "" {
		q = q.Where({{ $.Schema.EntSchemaPackageAlias }}.{{ .GoField }}(*createInput.{{ .GoField }}))
		hasKey = true
	}
{{ end -}}
{{- end }}
	if !hasKey {
		return ErrIngestUpsertKeyMissing
	}

	existing, err := q.Only(ctx)
	if err != nil {
		if !ent.IsNotFound(err) {
			if ent.IsNotSingular(err) {
				return ErrIngestUpsertConflict
			}

			return ErrIngestPersistFailed
		}

		if _, err := db.{{ .Schema.Name }}.Create().SetInput(createInput).Save(ctx); err != nil {
			return wrapIngestPersistError(err)
		}

		return nil
	}

	var updateInput ent.{{ .Schema.UpdateInputTypeName }}
	if err := jsonx.RoundTrip(createInput, &updateInput); err != nil {
		return ErrIngestMappedDocumentInvalid
	}

	if _, err := db.{{ .Schema.Name }}.UpdateOneID(existing.ID).SetInput(updateInput).Save(ctx); err != nil {
		return wrapIngestPersistError(err)
	}

	return nil
{{ else -}}
	// Custom persistence logic required for {{ .Schema.Name }}.
	// Implement lookup and upsert logic below using the createInput fields.
	panic("not implemented: persist{{ .Schema.Name }}Input")
{{ end -}}
}
