// Code generated by entx integration mapping generator. DO NOT EDIT.
package {{ .PackageName }}

{{- if .GenerateIngestContracts }}

import (
	generated "{{ .EntPackage }}"
	"{{ .GalaPackage }}"
)
{{- end }}


// IntegrationMappingField describes an integration mapping target field
type IntegrationMappingField struct {
	InputKey string
	GoField string
	EntField string
	Type string
	Required bool
	UpsertKey bool
	LookupKey bool
}

// IntegrationMappingSchema describes a schema with integration mapping fields
type IntegrationMappingSchema struct {
	Name string
	Fields []IntegrationMappingField
	AllowedKeys map[string]struct{}
	RequiredKeys []string
	UpsertKeys []string
}

// IntegrationIngestSchema describes schema-scoped ingest event contracts
type IntegrationIngestSchema struct {
	Name string
	Topic string
	Table string
	LookupFields []IntegrationIngestLookupField
	RuntimeDefaults []IntegrationIngestRuntimeDefault
	StockPersist bool
}

// IntegrationIngestLookupField describes one stock ingest lookup field
type IntegrationIngestLookupField struct {
	Field string
	GoField string
}

// IntegrationIngestRuntimeDefault describes one integration-injected field for stock ingest persistence
type IntegrationIngestRuntimeDefault struct {
	Field string
	GoField string
}

{{- if .GenerateIngestContracts }}

// IntegrationIngestSource identifies how a typed ingest request entered the ingest pipeline
type IntegrationIngestSource string

const (
	IntegrationIngestSourceOperation IntegrationIngestSource = "operation"
	IntegrationIngestSourceWorkflow IntegrationIngestSource = "workflow"
	IntegrationIngestSourceWebhook IntegrationIngestSource = "webhook"
	IntegrationIngestSourceDirect IntegrationIngestSource = "direct"
)

// IntegrationIngestMetadata captures source-agnostic execution context for second-stage ingest handlers
type IntegrationIngestMetadata struct {
	IntegrationID string `json:"integrationId"`
	DefinitionID string `json:"definitionId,omitempty"`
	Operation string `json:"operation,omitempty"`
	Variant string `json:"variant,omitempty"`
	Source IntegrationIngestSource `json:"source,omitempty"`
	RunID string `json:"runId,omitempty"`
	Webhook string `json:"webhook,omitempty"`
	WebhookEvent string `json:"webhookEvent,omitempty"`
	DeliveryID string `json:"deliveryId,omitempty"`
	WorkflowInstanceID string `json:"workflowInstanceId,omitempty"`
	WorkflowActionKey string `json:"workflowActionKey,omitempty"`
	WorkflowActionIndex int `json:"workflowActionIndex,omitempty"`
	WorkflowObjectID string `json:"workflowObjectId,omitempty"`
	WorkflowObjectType string `json:"workflowObjectType,omitempty"`
}
{{- end }}

const (
{{- range .Schemas }}
	{{ .ConstName }} = {{ printf "%q" .Name }}
{{- end }}
)

// Integration ingest topics by schema.
const (
{{- range .Schemas }}
	{{ .IngestTopicConstName }} = {{ printf "%q" .IngestTopic }}
{{- end }}
)

{{- if .GenerateIngestContracts }}

{{- range .Schemas }}

// {{ .IngestRequestTypeName }} is the typed second-stage ingest contract for {{ .Name }} records
type {{ .IngestRequestTypeName }} struct {
	Metadata IntegrationIngestMetadata `json:"metadata"`
	Input generated.{{ .InputTypeName }} `json:"input"`
}

// {{ .IngestTopicVarName }} is the typed Gala topic for {{ .Name }} ingest requests
var {{ .IngestTopicVarName }} = gala.Topic[{{ .IngestRequestTypeName }}]{
	Name: {{ .IngestTopicConstName }},
}
{{- end }}
{{- end }}

{{- range .Schemas }}

// Integration mapping keys for {{ .Name }}.
const (
{{- range .Fields }}
	{{ .ConstName }} = {{ printf "%q" .InputKey }}
{{- end }}
)
{{- end }}

// IntegrationMappingSchemas maps schema names to their mapping metadata
var IntegrationMappingSchemas = map[string]IntegrationMappingSchema{
{{- range .Schemas }}
	{{ printf "%q" .Name }}: {
		Name: {{ printf "%q" .Name }},
		Fields: []IntegrationMappingField{
		{{- range .Fields }}
			{
				InputKey: {{ printf "%q" .InputKey }},
				GoField: {{ printf "%q" .GoField }},
				EntField: {{ printf "%q" .EntField }},
				Type: {{ printf "%q" .Type }},
				Required: {{ .Required }},
				UpsertKey: {{ .UpsertKey }},
				LookupKey: {{ .LookupKey }},
			},
		{{- end }}
		},
		AllowedKeys: map[string]struct{}{
		{{- range .Fields }}
			{{ printf "%q" .InputKey }}: {},
		{{- end }}
		},
		RequiredKeys: []string{
		{{- range .Fields }}
			{{- if .Required }}
			{{ printf "%q" .InputKey }},
			{{- end }}
		{{- end }}
		},
		UpsertKeys: []string{
		{{- range .Fields }}
			{{- if .UpsertKey }}
			{{ printf "%q" .InputKey }},
			{{- end }}
		{{- end }}
		},
	},
{{- end }}
}

// IntegrationIngestSchemas maps schema names to schema-scoped ingest event contracts
var IntegrationIngestSchemas = map[string]IntegrationIngestSchema{
{{- range .Schemas }}
	{{ printf "%q" .Name }}: {
		Name: {{ printf "%q" .Name }},
		Topic: {{ printf "%q" .IngestTopic }},
		Table: {{ printf "%q" .TableName }},
		LookupFields: []IntegrationIngestLookupField{
		{{- range .LookupFields }}
			{
				Field: {{ printf "%q" .Field }},
				GoField: {{ printf "%q" .GoField }},
			},
		{{- end }}
		},
		RuntimeDefaults: []IntegrationIngestRuntimeDefault{
		{{- range .RuntimeDefaults }}
			{
				Field: {{ printf "%q" .Field }},
				GoField: {{ printf "%q" .GoField }},
			},
		{{- end }}
		},
		StockPersist: {{ .StockPersist }},
	},
{{- end }}
}

{{- if .GenerateIngestContracts }}
{{- range .Schemas }}
{{- if and .StockPersist .RuntimeDefaults }}

// Prepare{{ .Name }}Input stamps integration-scoped values onto a {{ .InputTypeName }} before persistence.
// Fields are only overwritten when the input value is already zero/nil.
func Prepare{{ .Name }}Input(input generated.{{ .InputTypeName }}, integration *generated.Integration) generated.{{ .InputTypeName }} {
	if integration == nil {
		return input
	}
{{- range .RuntimeDefaults }}
{{- if .Required }}
	if input.{{ .GoField }} == "" {
		input.{{ .GoField }} = integration.{{ .IntegrationField }}
	}
{{- else }}
	if input.{{ .GoField }} == nil && integration.{{ .IntegrationField }} != "" {
		input.{{ .GoField }} = &integration.{{ .IntegrationField }}
	}
{{- end }}
{{- end }}
	return input
}
{{- end }}
{{- end }}
{{- end }}
