// Code generated by ent (accessmap). DO NOT EDIT.

package generated

type EdgeAccess struct {
	ObjectType    string
	SkipEditCheck bool
}

// EdgeAccessMap maps <SchemaName> -> <edgeName> -> metadata.
// If an edge defines the accessmap.EdgeAccess annotation, its values are used.
// Otherwise, defaults are used: ObjectType = edge name, RequiresCheck = false.
var EdgeAccessMap = map[string]map[string]EdgeAccess{"org_membership": {"organization": {
	ObjectType:    "organization",
	SkipEditCheck: false,
},
}, "organization": {},
}
