// Code generated by ent (accessmap). DO NOT EDIT.

package generated

type EdgeAccess struct {
	ObjectType      string
	SkipEditCheck   bool
	CheckViewAccess bool
}

// EdgeAccessMap maps <SchemaName> -> <edgeName> -> metadata.
// If an edge defines the accessmap.EdgeAccess annotation, its values are used.
// Otherwise, defaults are used: ObjectType = edge name, SkipEditCheck = false.
var EdgeAccessMap = map[string]map[string]EdgeAccess{"org_membership": {"organization": {
	ObjectType:      "organization",
	SkipEditCheck:   false,
	CheckViewAccess: false,
},
}, "organization": {},
}
