// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
)

func (_m *OrgMembership) Organization(ctx context.Context) (*Organization, error) {
	result, err := _m.Edges.OrganizationOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryOrganization().Only(ctx)
	}
	return result, err
}
