// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"github.com/99designs/gqlgen/graphql"
)

func (_m *OrgMembership) Organization(ctx context.Context) (*Organization, error) {
	result, err := _m.Edges.OrganizationOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryOrganization().Only(ctx)
	}
	return result, err
}

func (_m *WorkflowObjectRef) WorkflowInstance(ctx context.Context) (*WorkflowInstance, error) {
	result, err := _m.Edges.WorkflowInstanceOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryWorkflowInstance().Only(ctx)
	}
	return result, err
}

func (_m *WorkflowObjectRef) Organization(ctx context.Context) (*Organization, error) {
	result, err := _m.Edges.OrganizationOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryOrganization().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (_m *WorkflowObjectRef) LinkedOrganizations(ctx context.Context) (result []*Organization, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedLinkedOrganizations(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.LinkedOrganizationsOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryLinkedOrganizations().All(ctx)
	}
	return result, err
}
