// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/theopenlane/entx/vanilla/_example/ent/predicate"
	"github.com/theopenlane/entx/vanilla/_example/ent/workflowinstance"
)

// WorkflowInstanceUpdate is the builder for updating WorkflowInstance entities.
type WorkflowInstanceUpdate struct {
	config
	hooks    []Hook
	mutation *WorkflowInstanceMutation
}

// Where appends a list predicates to the WorkflowInstanceUpdate builder.
func (_u *WorkflowInstanceUpdate) Where(ps ...predicate.WorkflowInstance) *WorkflowInstanceUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetStatus sets the "status" field.
func (_u *WorkflowInstanceUpdate) SetStatus(v string) *WorkflowInstanceUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *WorkflowInstanceUpdate) SetNillableStatus(v *string) *WorkflowInstanceUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// ClearStatus clears the value of the "status" field.
func (_u *WorkflowInstanceUpdate) ClearStatus() *WorkflowInstanceUpdate {
	_u.mutation.ClearStatus()
	return _u
}

// Mutation returns the WorkflowInstanceMutation object of the builder.
func (_u *WorkflowInstanceUpdate) Mutation() *WorkflowInstanceMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *WorkflowInstanceUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WorkflowInstanceUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *WorkflowInstanceUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WorkflowInstanceUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *WorkflowInstanceUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(workflowinstance.Table, workflowinstance.Columns, sqlgraph.NewFieldSpec(workflowinstance.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(workflowinstance.FieldStatus, field.TypeString, value)
	}
	if _u.mutation.StatusCleared() {
		_spec.ClearField(workflowinstance.FieldStatus, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{workflowinstance.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// WorkflowInstanceUpdateOne is the builder for updating a single WorkflowInstance entity.
type WorkflowInstanceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *WorkflowInstanceMutation
}

// SetStatus sets the "status" field.
func (_u *WorkflowInstanceUpdateOne) SetStatus(v string) *WorkflowInstanceUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *WorkflowInstanceUpdateOne) SetNillableStatus(v *string) *WorkflowInstanceUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// ClearStatus clears the value of the "status" field.
func (_u *WorkflowInstanceUpdateOne) ClearStatus() *WorkflowInstanceUpdateOne {
	_u.mutation.ClearStatus()
	return _u
}

// Mutation returns the WorkflowInstanceMutation object of the builder.
func (_u *WorkflowInstanceUpdateOne) Mutation() *WorkflowInstanceMutation {
	return _u.mutation
}

// Where appends a list predicates to the WorkflowInstanceUpdate builder.
func (_u *WorkflowInstanceUpdateOne) Where(ps ...predicate.WorkflowInstance) *WorkflowInstanceUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *WorkflowInstanceUpdateOne) Select(field string, fields ...string) *WorkflowInstanceUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated WorkflowInstance entity.
func (_u *WorkflowInstanceUpdateOne) Save(ctx context.Context) (*WorkflowInstance, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WorkflowInstanceUpdateOne) SaveX(ctx context.Context) *WorkflowInstance {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *WorkflowInstanceUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WorkflowInstanceUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *WorkflowInstanceUpdateOne) sqlSave(ctx context.Context) (_node *WorkflowInstance, err error) {
	_spec := sqlgraph.NewUpdateSpec(workflowinstance.Table, workflowinstance.Columns, sqlgraph.NewFieldSpec(workflowinstance.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "WorkflowInstance.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, workflowinstance.FieldID)
		for _, f := range fields {
			if !workflowinstance.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != workflowinstance.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(workflowinstance.FieldStatus, field.TypeString, value)
	}
	if _u.mutation.StatusCleared() {
		_spec.ClearField(workflowinstance.FieldStatus, field.TypeString)
	}
	_node = &WorkflowInstance{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{workflowinstance.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
