// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/theopenlane/entx/vanilla/_example/ent/organization"
	"github.com/theopenlane/entx/vanilla/_example/ent/predicate"
	"github.com/theopenlane/entx/vanilla/_example/ent/workflowinstance"
	"github.com/theopenlane/entx/vanilla/_example/ent/workflowobjectref"
)

// WorkflowObjectRefQuery is the builder for querying WorkflowObjectRef entities.
type WorkflowObjectRefQuery struct {
	config
	ctx                  *QueryContext
	order                []workflowobjectref.OrderOption
	inters               []Interceptor
	predicates           []predicate.WorkflowObjectRef
	withWorkflowInstance *WorkflowInstanceQuery
	withOrganization     *OrganizationQuery
	modifiers            []func(*sql.Selector)
	loadTotal            []func(context.Context, []*WorkflowObjectRef) error
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the WorkflowObjectRefQuery builder.
func (_q *WorkflowObjectRefQuery) Where(ps ...predicate.WorkflowObjectRef) *WorkflowObjectRefQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *WorkflowObjectRefQuery) Limit(limit int) *WorkflowObjectRefQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *WorkflowObjectRefQuery) Offset(offset int) *WorkflowObjectRefQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *WorkflowObjectRefQuery) Unique(unique bool) *WorkflowObjectRefQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *WorkflowObjectRefQuery) Order(o ...workflowobjectref.OrderOption) *WorkflowObjectRefQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryWorkflowInstance chains the current query on the "workflow_instance" edge.
func (_q *WorkflowObjectRefQuery) QueryWorkflowInstance() *WorkflowInstanceQuery {
	query := (&WorkflowInstanceClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(workflowobjectref.Table, workflowobjectref.FieldID, selector),
			sqlgraph.To(workflowinstance.Table, workflowinstance.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, workflowobjectref.WorkflowInstanceTable, workflowobjectref.WorkflowInstanceColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryOrganization chains the current query on the "organization" edge.
func (_q *WorkflowObjectRefQuery) QueryOrganization() *OrganizationQuery {
	query := (&OrganizationClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(workflowobjectref.Table, workflowobjectref.FieldID, selector),
			sqlgraph.To(organization.Table, organization.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, workflowobjectref.OrganizationTable, workflowobjectref.OrganizationColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first WorkflowObjectRef entity from the query.
// Returns a *NotFoundError when no WorkflowObjectRef was found.
func (_q *WorkflowObjectRefQuery) First(ctx context.Context) (*WorkflowObjectRef, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{workflowobjectref.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *WorkflowObjectRefQuery) FirstX(ctx context.Context) *WorkflowObjectRef {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first WorkflowObjectRef ID from the query.
// Returns a *NotFoundError when no WorkflowObjectRef ID was found.
func (_q *WorkflowObjectRefQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{workflowobjectref.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *WorkflowObjectRefQuery) FirstIDX(ctx context.Context) string {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single WorkflowObjectRef entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one WorkflowObjectRef entity is found.
// Returns a *NotFoundError when no WorkflowObjectRef entities are found.
func (_q *WorkflowObjectRefQuery) Only(ctx context.Context) (*WorkflowObjectRef, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{workflowobjectref.Label}
	default:
		return nil, &NotSingularError{workflowobjectref.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *WorkflowObjectRefQuery) OnlyX(ctx context.Context) *WorkflowObjectRef {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only WorkflowObjectRef ID in the query.
// Returns a *NotSingularError when more than one WorkflowObjectRef ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *WorkflowObjectRefQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{workflowobjectref.Label}
	default:
		err = &NotSingularError{workflowobjectref.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *WorkflowObjectRefQuery) OnlyIDX(ctx context.Context) string {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of WorkflowObjectRefs.
func (_q *WorkflowObjectRefQuery) All(ctx context.Context) ([]*WorkflowObjectRef, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*WorkflowObjectRef, *WorkflowObjectRefQuery]()
	return withInterceptors[[]*WorkflowObjectRef](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *WorkflowObjectRefQuery) AllX(ctx context.Context) []*WorkflowObjectRef {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of WorkflowObjectRef IDs.
func (_q *WorkflowObjectRefQuery) IDs(ctx context.Context) (ids []string, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(workflowobjectref.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *WorkflowObjectRefQuery) IDsX(ctx context.Context) []string {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *WorkflowObjectRefQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*WorkflowObjectRefQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *WorkflowObjectRefQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *WorkflowObjectRefQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *WorkflowObjectRefQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the WorkflowObjectRefQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *WorkflowObjectRefQuery) Clone() *WorkflowObjectRefQuery {
	if _q == nil {
		return nil
	}
	return &WorkflowObjectRefQuery{
		config:               _q.config,
		ctx:                  _q.ctx.Clone(),
		order:                append([]workflowobjectref.OrderOption{}, _q.order...),
		inters:               append([]Interceptor{}, _q.inters...),
		predicates:           append([]predicate.WorkflowObjectRef{}, _q.predicates...),
		withWorkflowInstance: _q.withWorkflowInstance.Clone(),
		withOrganization:     _q.withOrganization.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithWorkflowInstance tells the query-builder to eager-load the nodes that are connected to
// the "workflow_instance" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *WorkflowObjectRefQuery) WithWorkflowInstance(opts ...func(*WorkflowInstanceQuery)) *WorkflowObjectRefQuery {
	query := (&WorkflowInstanceClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withWorkflowInstance = query
	return _q
}

// WithOrganization tells the query-builder to eager-load the nodes that are connected to
// the "organization" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *WorkflowObjectRefQuery) WithOrganization(opts ...func(*OrganizationQuery)) *WorkflowObjectRefQuery {
	query := (&OrganizationClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withOrganization = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		WorkflowInstanceID string `json:"workflow_instance_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.WorkflowObjectRef.Query().
//		GroupBy(workflowobjectref.FieldWorkflowInstanceID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *WorkflowObjectRefQuery) GroupBy(field string, fields ...string) *WorkflowObjectRefGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &WorkflowObjectRefGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = workflowobjectref.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		WorkflowInstanceID string `json:"workflow_instance_id,omitempty"`
//	}
//
//	client.WorkflowObjectRef.Query().
//		Select(workflowobjectref.FieldWorkflowInstanceID).
//		Scan(ctx, &v)
func (_q *WorkflowObjectRefQuery) Select(fields ...string) *WorkflowObjectRefSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &WorkflowObjectRefSelect{WorkflowObjectRefQuery: _q}
	sbuild.label = workflowobjectref.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a WorkflowObjectRefSelect configured with the given aggregations.
func (_q *WorkflowObjectRefQuery) Aggregate(fns ...AggregateFunc) *WorkflowObjectRefSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *WorkflowObjectRefQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !workflowobjectref.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *WorkflowObjectRefQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*WorkflowObjectRef, error) {
	var (
		nodes       = []*WorkflowObjectRef{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withWorkflowInstance != nil,
			_q.withOrganization != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*WorkflowObjectRef).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &WorkflowObjectRef{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withWorkflowInstance; query != nil {
		if err := _q.loadWorkflowInstance(ctx, query, nodes, nil,
			func(n *WorkflowObjectRef, e *WorkflowInstance) { n.Edges.WorkflowInstance = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withOrganization; query != nil {
		if err := _q.loadOrganization(ctx, query, nodes, nil,
			func(n *WorkflowObjectRef, e *Organization) { n.Edges.Organization = e }); err != nil {
			return nil, err
		}
	}
	for i := range _q.loadTotal {
		if err := _q.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *WorkflowObjectRefQuery) loadWorkflowInstance(ctx context.Context, query *WorkflowInstanceQuery, nodes []*WorkflowObjectRef, init func(*WorkflowObjectRef), assign func(*WorkflowObjectRef, *WorkflowInstance)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*WorkflowObjectRef)
	for i := range nodes {
		fk := nodes[i].WorkflowInstanceID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(workflowinstance.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "workflow_instance_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *WorkflowObjectRefQuery) loadOrganization(ctx context.Context, query *OrganizationQuery, nodes []*WorkflowObjectRef, init func(*WorkflowObjectRef), assign func(*WorkflowObjectRef, *Organization)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*WorkflowObjectRef)
	for i := range nodes {
		fk := nodes[i].OrganizationID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(organization.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "organization_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *WorkflowObjectRefQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *WorkflowObjectRefQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(workflowobjectref.Table, workflowobjectref.Columns, sqlgraph.NewFieldSpec(workflowobjectref.FieldID, field.TypeString))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, workflowobjectref.FieldID)
		for i := range fields {
			if fields[i] != workflowobjectref.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withWorkflowInstance != nil {
			_spec.Node.AddColumnOnce(workflowobjectref.FieldWorkflowInstanceID)
		}
		if _q.withOrganization != nil {
			_spec.Node.AddColumnOnce(workflowobjectref.FieldOrganizationID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *WorkflowObjectRefQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(workflowobjectref.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = workflowobjectref.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// WorkflowObjectRefGroupBy is the group-by builder for WorkflowObjectRef entities.
type WorkflowObjectRefGroupBy struct {
	selector
	build *WorkflowObjectRefQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *WorkflowObjectRefGroupBy) Aggregate(fns ...AggregateFunc) *WorkflowObjectRefGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *WorkflowObjectRefGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*WorkflowObjectRefQuery, *WorkflowObjectRefGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *WorkflowObjectRefGroupBy) sqlScan(ctx context.Context, root *WorkflowObjectRefQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// WorkflowObjectRefSelect is the builder for selecting fields of WorkflowObjectRef entities.
type WorkflowObjectRefSelect struct {
	*WorkflowObjectRefQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *WorkflowObjectRefSelect) Aggregate(fns ...AggregateFunc) *WorkflowObjectRefSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *WorkflowObjectRefSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*WorkflowObjectRefQuery, *WorkflowObjectRefSelect](ctx, _s.WorkflowObjectRefQuery, _s, _s.inters, v)
}

func (_s *WorkflowObjectRefSelect) sqlScan(ctx context.Context, root *WorkflowObjectRefQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
