// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/theopenlane/entx/vanilla/_example/ent/organization"
	"github.com/theopenlane/entx/vanilla/_example/ent/predicate"
	"github.com/theopenlane/entx/vanilla/_example/ent/workflowobjectref"
)

// WorkflowObjectRefUpdate is the builder for updating WorkflowObjectRef entities.
type WorkflowObjectRefUpdate struct {
	config
	hooks    []Hook
	mutation *WorkflowObjectRefMutation
}

// Where appends a list predicates to the WorkflowObjectRefUpdate builder.
func (_u *WorkflowObjectRefUpdate) Where(ps ...predicate.WorkflowObjectRef) *WorkflowObjectRefUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// AddLinkedOrganizationIDs adds the "linked_organizations" edge to the Organization entity by IDs.
func (_u *WorkflowObjectRefUpdate) AddLinkedOrganizationIDs(ids ...string) *WorkflowObjectRefUpdate {
	_u.mutation.AddLinkedOrganizationIDs(ids...)
	return _u
}

// AddLinkedOrganizations adds the "linked_organizations" edges to the Organization entity.
func (_u *WorkflowObjectRefUpdate) AddLinkedOrganizations(v ...*Organization) *WorkflowObjectRefUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddLinkedOrganizationIDs(ids...)
}

// Mutation returns the WorkflowObjectRefMutation object of the builder.
func (_u *WorkflowObjectRefUpdate) Mutation() *WorkflowObjectRefMutation {
	return _u.mutation
}

// ClearLinkedOrganizations clears all "linked_organizations" edges to the Organization entity.
func (_u *WorkflowObjectRefUpdate) ClearLinkedOrganizations() *WorkflowObjectRefUpdate {
	_u.mutation.ClearLinkedOrganizations()
	return _u
}

// RemoveLinkedOrganizationIDs removes the "linked_organizations" edge to Organization entities by IDs.
func (_u *WorkflowObjectRefUpdate) RemoveLinkedOrganizationIDs(ids ...string) *WorkflowObjectRefUpdate {
	_u.mutation.RemoveLinkedOrganizationIDs(ids...)
	return _u
}

// RemoveLinkedOrganizations removes "linked_organizations" edges to Organization entities.
func (_u *WorkflowObjectRefUpdate) RemoveLinkedOrganizations(v ...*Organization) *WorkflowObjectRefUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveLinkedOrganizationIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *WorkflowObjectRefUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WorkflowObjectRefUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *WorkflowObjectRefUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WorkflowObjectRefUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *WorkflowObjectRefUpdate) check() error {
	if _u.mutation.WorkflowInstanceCleared() && len(_u.mutation.WorkflowInstanceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "WorkflowObjectRef.workflow_instance"`)
	}
	return nil
}

func (_u *WorkflowObjectRefUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(workflowobjectref.Table, workflowobjectref.Columns, sqlgraph.NewFieldSpec(workflowobjectref.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.LinkedOrganizationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workflowobjectref.LinkedOrganizationsTable,
			Columns: []string{workflowobjectref.LinkedOrganizationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedLinkedOrganizationsIDs(); len(nodes) > 0 && !_u.mutation.LinkedOrganizationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workflowobjectref.LinkedOrganizationsTable,
			Columns: []string{workflowobjectref.LinkedOrganizationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LinkedOrganizationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workflowobjectref.LinkedOrganizationsTable,
			Columns: []string{workflowobjectref.LinkedOrganizationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{workflowobjectref.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// WorkflowObjectRefUpdateOne is the builder for updating a single WorkflowObjectRef entity.
type WorkflowObjectRefUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *WorkflowObjectRefMutation
}

// AddLinkedOrganizationIDs adds the "linked_organizations" edge to the Organization entity by IDs.
func (_u *WorkflowObjectRefUpdateOne) AddLinkedOrganizationIDs(ids ...string) *WorkflowObjectRefUpdateOne {
	_u.mutation.AddLinkedOrganizationIDs(ids...)
	return _u
}

// AddLinkedOrganizations adds the "linked_organizations" edges to the Organization entity.
func (_u *WorkflowObjectRefUpdateOne) AddLinkedOrganizations(v ...*Organization) *WorkflowObjectRefUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddLinkedOrganizationIDs(ids...)
}

// Mutation returns the WorkflowObjectRefMutation object of the builder.
func (_u *WorkflowObjectRefUpdateOne) Mutation() *WorkflowObjectRefMutation {
	return _u.mutation
}

// ClearLinkedOrganizations clears all "linked_organizations" edges to the Organization entity.
func (_u *WorkflowObjectRefUpdateOne) ClearLinkedOrganizations() *WorkflowObjectRefUpdateOne {
	_u.mutation.ClearLinkedOrganizations()
	return _u
}

// RemoveLinkedOrganizationIDs removes the "linked_organizations" edge to Organization entities by IDs.
func (_u *WorkflowObjectRefUpdateOne) RemoveLinkedOrganizationIDs(ids ...string) *WorkflowObjectRefUpdateOne {
	_u.mutation.RemoveLinkedOrganizationIDs(ids...)
	return _u
}

// RemoveLinkedOrganizations removes "linked_organizations" edges to Organization entities.
func (_u *WorkflowObjectRefUpdateOne) RemoveLinkedOrganizations(v ...*Organization) *WorkflowObjectRefUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveLinkedOrganizationIDs(ids...)
}

// Where appends a list predicates to the WorkflowObjectRefUpdate builder.
func (_u *WorkflowObjectRefUpdateOne) Where(ps ...predicate.WorkflowObjectRef) *WorkflowObjectRefUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *WorkflowObjectRefUpdateOne) Select(field string, fields ...string) *WorkflowObjectRefUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated WorkflowObjectRef entity.
func (_u *WorkflowObjectRefUpdateOne) Save(ctx context.Context) (*WorkflowObjectRef, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WorkflowObjectRefUpdateOne) SaveX(ctx context.Context) *WorkflowObjectRef {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *WorkflowObjectRefUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WorkflowObjectRefUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *WorkflowObjectRefUpdateOne) check() error {
	if _u.mutation.WorkflowInstanceCleared() && len(_u.mutation.WorkflowInstanceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "WorkflowObjectRef.workflow_instance"`)
	}
	return nil
}

func (_u *WorkflowObjectRefUpdateOne) sqlSave(ctx context.Context) (_node *WorkflowObjectRef, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(workflowobjectref.Table, workflowobjectref.Columns, sqlgraph.NewFieldSpec(workflowobjectref.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "WorkflowObjectRef.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, workflowobjectref.FieldID)
		for _, f := range fields {
			if !workflowobjectref.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != workflowobjectref.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.LinkedOrganizationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workflowobjectref.LinkedOrganizationsTable,
			Columns: []string{workflowobjectref.LinkedOrganizationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedLinkedOrganizationsIDs(); len(nodes) > 0 && !_u.mutation.LinkedOrganizationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workflowobjectref.LinkedOrganizationsTable,
			Columns: []string{workflowobjectref.LinkedOrganizationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LinkedOrganizationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workflowobjectref.LinkedOrganizationsTable,
			Columns: []string{workflowobjectref.LinkedOrganizationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &WorkflowObjectRef{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{workflowobjectref.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
