env:
  APP_NAME: ${BUILDKITE_PIPELINE_SLUG}
  IMAGE_REPO: ghcr.io/theopenlane/${APP_NAME}
  SONAR_HOST: "https://sonarcloud.io"
steps:
  - group: ":test_tube: Tests"
    key: "tests"
    steps:
      - label: ":golangci-lint: lint :lint-roller:"
        key: "lint"
        plugins:
          - docker#v5.12.0:
              image: "golangci/golangci-lint:latest-alpine"
              cancel_on_build_failing: true
              command: ["golangci-lint", "run", "-v"]
              always-pull: true
              environment:
                - "GOTOOLCHAIN=auto"
      - label: ":golang: go test"
        key: "go_test"
        plugins:
          - docker#v5.12.0:
              image: golang:1.24.4
              command: ["go", "test", "-coverprofile=coverage.out", "./..."]
        artifact_paths: ["coverage.out"]
      - label: ":github: upload PR reports"
        key: "scan-upload-pr"
        if: build.pull_request.id != null
        depends_on: ["go_test"]
        plugins:
          - cluster-secrets#v1.0.0:
              variables:
                SONAR_TOKEN: SONAR_TOKEN
          - artifacts#v1.9.4:
              download: "coverage.out"
              step: "go_test"
          - docker#v5.12.0:
              image: "sonarsource/sonar-scanner-cli:11.0"
              environment:
                - "SONAR_TOKEN"
                - "SONAR_HOST_URL=$SONAR_HOST"
                - "SONAR_SCANNER_OPTS=-Dsonar.pullrequest.branch=$BUILDKITE_BRANCH -Dsonar.pullrequest.base=$BUILDKITE_PULL_REQUEST_BASE_BRANCH -Dsonar.pullrequest.key=$BUILDKITE_PULL_REQUEST"
      - label: ":github: upload reports"
        key: "scan-upload"
        if: build.branch == "main"
        depends_on: ["go_test"]
        plugins:
          - cluster-secrets#v1.0.0:
              variables:
                SONAR_TOKEN: SONAR_TOKEN
          - artifacts#v1.9.4:
              download: coverage.out
              step: "go_test"
          - docker#v5.12.0:
              image: "sonarsource/sonar-scanner-cli:11.0"
              environment:
                - "SONAR_TOKEN"
                - "SONAR_HOST_URL=$SONAR_HOST"
