// Code generated by ent, DO NOT EDIT.

package workflowobjectref

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/theopenlane/entx/vanilla/_example/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.WorkflowObjectRef {
	return predicate.WorkflowObjectRef(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.WorkflowObjectRef {
	return predicate.WorkflowObjectRef(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.WorkflowObjectRef {
	return predicate.WorkflowObjectRef(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.WorkflowObjectRef {
	return predicate.WorkflowObjectRef(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.WorkflowObjectRef {
	return predicate.WorkflowObjectRef(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.WorkflowObjectRef {
	return predicate.WorkflowObjectRef(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.WorkflowObjectRef {
	return predicate.WorkflowObjectRef(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.WorkflowObjectRef {
	return predicate.WorkflowObjectRef(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.WorkflowObjectRef {
	return predicate.WorkflowObjectRef(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.WorkflowObjectRef {
	return predicate.WorkflowObjectRef(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.WorkflowObjectRef {
	return predicate.WorkflowObjectRef(sql.FieldContainsFold(FieldID, id))
}

// WorkflowInstanceID applies equality check predicate on the "workflow_instance_id" field. It's identical to WorkflowInstanceIDEQ.
func WorkflowInstanceID(v string) predicate.WorkflowObjectRef {
	return predicate.WorkflowObjectRef(sql.FieldEQ(FieldWorkflowInstanceID, v))
}

// OrganizationID applies equality check predicate on the "organization_id" field. It's identical to OrganizationIDEQ.
func OrganizationID(v string) predicate.WorkflowObjectRef {
	return predicate.WorkflowObjectRef(sql.FieldEQ(FieldOrganizationID, v))
}

// WorkflowInstanceIDEQ applies the EQ predicate on the "workflow_instance_id" field.
func WorkflowInstanceIDEQ(v string) predicate.WorkflowObjectRef {
	return predicate.WorkflowObjectRef(sql.FieldEQ(FieldWorkflowInstanceID, v))
}

// WorkflowInstanceIDNEQ applies the NEQ predicate on the "workflow_instance_id" field.
func WorkflowInstanceIDNEQ(v string) predicate.WorkflowObjectRef {
	return predicate.WorkflowObjectRef(sql.FieldNEQ(FieldWorkflowInstanceID, v))
}

// WorkflowInstanceIDIn applies the In predicate on the "workflow_instance_id" field.
func WorkflowInstanceIDIn(vs ...string) predicate.WorkflowObjectRef {
	return predicate.WorkflowObjectRef(sql.FieldIn(FieldWorkflowInstanceID, vs...))
}

// WorkflowInstanceIDNotIn applies the NotIn predicate on the "workflow_instance_id" field.
func WorkflowInstanceIDNotIn(vs ...string) predicate.WorkflowObjectRef {
	return predicate.WorkflowObjectRef(sql.FieldNotIn(FieldWorkflowInstanceID, vs...))
}

// WorkflowInstanceIDGT applies the GT predicate on the "workflow_instance_id" field.
func WorkflowInstanceIDGT(v string) predicate.WorkflowObjectRef {
	return predicate.WorkflowObjectRef(sql.FieldGT(FieldWorkflowInstanceID, v))
}

// WorkflowInstanceIDGTE applies the GTE predicate on the "workflow_instance_id" field.
func WorkflowInstanceIDGTE(v string) predicate.WorkflowObjectRef {
	return predicate.WorkflowObjectRef(sql.FieldGTE(FieldWorkflowInstanceID, v))
}

// WorkflowInstanceIDLT applies the LT predicate on the "workflow_instance_id" field.
func WorkflowInstanceIDLT(v string) predicate.WorkflowObjectRef {
	return predicate.WorkflowObjectRef(sql.FieldLT(FieldWorkflowInstanceID, v))
}

// WorkflowInstanceIDLTE applies the LTE predicate on the "workflow_instance_id" field.
func WorkflowInstanceIDLTE(v string) predicate.WorkflowObjectRef {
	return predicate.WorkflowObjectRef(sql.FieldLTE(FieldWorkflowInstanceID, v))
}

// WorkflowInstanceIDContains applies the Contains predicate on the "workflow_instance_id" field.
func WorkflowInstanceIDContains(v string) predicate.WorkflowObjectRef {
	return predicate.WorkflowObjectRef(sql.FieldContains(FieldWorkflowInstanceID, v))
}

// WorkflowInstanceIDHasPrefix applies the HasPrefix predicate on the "workflow_instance_id" field.
func WorkflowInstanceIDHasPrefix(v string) predicate.WorkflowObjectRef {
	return predicate.WorkflowObjectRef(sql.FieldHasPrefix(FieldWorkflowInstanceID, v))
}

// WorkflowInstanceIDHasSuffix applies the HasSuffix predicate on the "workflow_instance_id" field.
func WorkflowInstanceIDHasSuffix(v string) predicate.WorkflowObjectRef {
	return predicate.WorkflowObjectRef(sql.FieldHasSuffix(FieldWorkflowInstanceID, v))
}

// WorkflowInstanceIDEqualFold applies the EqualFold predicate on the "workflow_instance_id" field.
func WorkflowInstanceIDEqualFold(v string) predicate.WorkflowObjectRef {
	return predicate.WorkflowObjectRef(sql.FieldEqualFold(FieldWorkflowInstanceID, v))
}

// WorkflowInstanceIDContainsFold applies the ContainsFold predicate on the "workflow_instance_id" field.
func WorkflowInstanceIDContainsFold(v string) predicate.WorkflowObjectRef {
	return predicate.WorkflowObjectRef(sql.FieldContainsFold(FieldWorkflowInstanceID, v))
}

// OrganizationIDEQ applies the EQ predicate on the "organization_id" field.
func OrganizationIDEQ(v string) predicate.WorkflowObjectRef {
	return predicate.WorkflowObjectRef(sql.FieldEQ(FieldOrganizationID, v))
}

// OrganizationIDNEQ applies the NEQ predicate on the "organization_id" field.
func OrganizationIDNEQ(v string) predicate.WorkflowObjectRef {
	return predicate.WorkflowObjectRef(sql.FieldNEQ(FieldOrganizationID, v))
}

// OrganizationIDIn applies the In predicate on the "organization_id" field.
func OrganizationIDIn(vs ...string) predicate.WorkflowObjectRef {
	return predicate.WorkflowObjectRef(sql.FieldIn(FieldOrganizationID, vs...))
}

// OrganizationIDNotIn applies the NotIn predicate on the "organization_id" field.
func OrganizationIDNotIn(vs ...string) predicate.WorkflowObjectRef {
	return predicate.WorkflowObjectRef(sql.FieldNotIn(FieldOrganizationID, vs...))
}

// OrganizationIDGT applies the GT predicate on the "organization_id" field.
func OrganizationIDGT(v string) predicate.WorkflowObjectRef {
	return predicate.WorkflowObjectRef(sql.FieldGT(FieldOrganizationID, v))
}

// OrganizationIDGTE applies the GTE predicate on the "organization_id" field.
func OrganizationIDGTE(v string) predicate.WorkflowObjectRef {
	return predicate.WorkflowObjectRef(sql.FieldGTE(FieldOrganizationID, v))
}

// OrganizationIDLT applies the LT predicate on the "organization_id" field.
func OrganizationIDLT(v string) predicate.WorkflowObjectRef {
	return predicate.WorkflowObjectRef(sql.FieldLT(FieldOrganizationID, v))
}

// OrganizationIDLTE applies the LTE predicate on the "organization_id" field.
func OrganizationIDLTE(v string) predicate.WorkflowObjectRef {
	return predicate.WorkflowObjectRef(sql.FieldLTE(FieldOrganizationID, v))
}

// OrganizationIDContains applies the Contains predicate on the "organization_id" field.
func OrganizationIDContains(v string) predicate.WorkflowObjectRef {
	return predicate.WorkflowObjectRef(sql.FieldContains(FieldOrganizationID, v))
}

// OrganizationIDHasPrefix applies the HasPrefix predicate on the "organization_id" field.
func OrganizationIDHasPrefix(v string) predicate.WorkflowObjectRef {
	return predicate.WorkflowObjectRef(sql.FieldHasPrefix(FieldOrganizationID, v))
}

// OrganizationIDHasSuffix applies the HasSuffix predicate on the "organization_id" field.
func OrganizationIDHasSuffix(v string) predicate.WorkflowObjectRef {
	return predicate.WorkflowObjectRef(sql.FieldHasSuffix(FieldOrganizationID, v))
}

// OrganizationIDIsNil applies the IsNil predicate on the "organization_id" field.
func OrganizationIDIsNil() predicate.WorkflowObjectRef {
	return predicate.WorkflowObjectRef(sql.FieldIsNull(FieldOrganizationID))
}

// OrganizationIDNotNil applies the NotNil predicate on the "organization_id" field.
func OrganizationIDNotNil() predicate.WorkflowObjectRef {
	return predicate.WorkflowObjectRef(sql.FieldNotNull(FieldOrganizationID))
}

// OrganizationIDEqualFold applies the EqualFold predicate on the "organization_id" field.
func OrganizationIDEqualFold(v string) predicate.WorkflowObjectRef {
	return predicate.WorkflowObjectRef(sql.FieldEqualFold(FieldOrganizationID, v))
}

// OrganizationIDContainsFold applies the ContainsFold predicate on the "organization_id" field.
func OrganizationIDContainsFold(v string) predicate.WorkflowObjectRef {
	return predicate.WorkflowObjectRef(sql.FieldContainsFold(FieldOrganizationID, v))
}

// HasWorkflowInstance applies the HasEdge predicate on the "workflow_instance" edge.
func HasWorkflowInstance() predicate.WorkflowObjectRef {
	return predicate.WorkflowObjectRef(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, WorkflowInstanceTable, WorkflowInstanceColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasWorkflowInstanceWith applies the HasEdge predicate on the "workflow_instance" edge with a given conditions (other predicates).
func HasWorkflowInstanceWith(preds ...predicate.WorkflowInstance) predicate.WorkflowObjectRef {
	return predicate.WorkflowObjectRef(func(s *sql.Selector) {
		step := newWorkflowInstanceStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasOrganization applies the HasEdge predicate on the "organization" edge.
func HasOrganization() predicate.WorkflowObjectRef {
	return predicate.WorkflowObjectRef(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, OrganizationTable, OrganizationColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOrganizationWith applies the HasEdge predicate on the "organization" edge with a given conditions (other predicates).
func HasOrganizationWith(preds ...predicate.Organization) predicate.WorkflowObjectRef {
	return predicate.WorkflowObjectRef(func(s *sql.Selector) {
		step := newOrganizationStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.WorkflowObjectRef) predicate.WorkflowObjectRef {
	return predicate.WorkflowObjectRef(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.WorkflowObjectRef) predicate.WorkflowObjectRef {
	return predicate.WorkflowObjectRef(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.WorkflowObjectRef) predicate.WorkflowObjectRef {
	return predicate.WorkflowObjectRef(sql.NotPredicates(p))
}
