// Code generated by ent, DO NOT EDIT.

package workflowobjectref

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the workflowobjectref type in the database.
	Label = "workflow_object_ref"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldWorkflowInstanceID holds the string denoting the workflow_instance_id field in the database.
	FieldWorkflowInstanceID = "workflow_instance_id"
	// FieldOrganizationID holds the string denoting the organization_id field in the database.
	FieldOrganizationID = "organization_id"
	// EdgeWorkflowInstance holds the string denoting the workflow_instance edge name in mutations.
	EdgeWorkflowInstance = "workflow_instance"
	// EdgeOrganization holds the string denoting the organization edge name in mutations.
	EdgeOrganization = "organization"
	// Table holds the table name of the workflowobjectref in the database.
	Table = "workflow_object_refs"
	// WorkflowInstanceTable is the table that holds the workflow_instance relation/edge.
	WorkflowInstanceTable = "workflow_object_refs"
	// WorkflowInstanceInverseTable is the table name for the WorkflowInstance entity.
	// It exists in this package in order to avoid circular dependency with the "workflowinstance" package.
	WorkflowInstanceInverseTable = "workflow_instances"
	// WorkflowInstanceColumn is the table column denoting the workflow_instance relation/edge.
	WorkflowInstanceColumn = "workflow_instance_id"
	// OrganizationTable is the table that holds the organization relation/edge.
	OrganizationTable = "workflow_object_refs"
	// OrganizationInverseTable is the table name for the Organization entity.
	// It exists in this package in order to avoid circular dependency with the "organization" package.
	OrganizationInverseTable = "organizations"
	// OrganizationColumn is the table column denoting the organization relation/edge.
	OrganizationColumn = "organization_id"
)

// Columns holds all SQL columns for workflowobjectref fields.
var Columns = []string{
	FieldID,
	FieldWorkflowInstanceID,
	FieldOrganizationID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the WorkflowObjectRef queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByWorkflowInstanceID orders the results by the workflow_instance_id field.
func ByWorkflowInstanceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWorkflowInstanceID, opts...).ToFunc()
}

// ByOrganizationID orders the results by the organization_id field.
func ByOrganizationID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrganizationID, opts...).ToFunc()
}

// ByWorkflowInstanceField orders the results by workflow_instance field.
func ByWorkflowInstanceField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newWorkflowInstanceStep(), sql.OrderByField(field, opts...))
	}
}

// ByOrganizationField orders the results by organization field.
func ByOrganizationField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newOrganizationStep(), sql.OrderByField(field, opts...))
	}
}
func newWorkflowInstanceStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(WorkflowInstanceInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, WorkflowInstanceTable, WorkflowInstanceColumn),
	)
}
func newOrganizationStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(OrganizationInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, OrganizationTable, OrganizationColumn),
	)
}
