// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// OrgMembership is the predicate function for orgmembership builders.
type OrgMembership func(*sql.Selector)

// Organization is the predicate function for organization builders.
type Organization func(*sql.Selector)
